import { readFile, writeFile, mkdir, rm, cp } from 'node:fs/promises';
import { appearanceOptions, defaultAppearance, residencyState, institutionRequirements } from '../worker/residency.js';
import {districtSnapshot} from '../worker/life.js';
import {supplyCatalog} from '../worker/orders.js';
import { streetSnapshot } from '../worker/street.js';
import { cityResponses } from '../worker/citylife.js';
import {livingSnapshot} from '../worker/living.js';
import {stairState,alphaProgress} from '../worker/neighborhood.js';
import { initial, world, goods, jobs } from '../worker/game.js';
import { encountersFor, personalState } from '../worker/stories.js';
import { forceProfile, citizenForces } from '../worker/forces.js';
import { careerState, gearEffects, shiftTypes, jobQuote, careerSnapshot, equipmentSnapshot, gearCatalog } from '../worker/progression.js';
await rm('dist',{recursive:true,force:true});await mkdir('dist/server',{recursive:true});await mkdir('dist/.openai',{recursive:true});
const seed={citizen:{id:'pending',name:'Unregistered citizen',...initial()},world:world(),goods:Object.entries(goods).map(([id,g])=>({id,...g})),jobs:Object.entries(jobs).map(([id,j])=>({id,...j})),log:[],board:[],citizens:[],listings:[],totals:{citizens:0,members:0}};
residencyState(seed.citizen,Date.now());seed.streetLife=streetSnapshot(seed.citizen,seed.world);seed.network=[];seed.districtLife=districtSnapshot(seed.citizen,seed.world);seed.supplyExchange={catalog:supplyCatalog,orders:[],municipalUsed:0,slots:3};seed.crisisResponses=[];seed.living=livingSnapshot(seed.citizen,seed.world);seed.tenants={block:null,directory:[],capacity:12,catalog:supplyCatalog};seed.recoveryOptions=[];seed.appearanceOptions=appearanceOptions;seed.requirements=institutionRequirements(seed.citizen,Date.now());seed.idFlags=[];seed.cityLife={metrics:{output:0,freight:0,crime:0,unrest:0,relief:0,patrols:0},target:6,events:[],aftermath:{incidents:[],paper:[]},responses:cityResponses,workLimit:8,crimeLimit:3};
personalState(seed.citizen);seed.encounters=encountersFor(seed.citizen);seed.project={progress:0,target:12,complete:false};
citizenForces(seed.citizen);seed.forces={...forceProfile(),day:seed.world.day};Object.assign(seed.world,forceProfile());seed.encounters=encountersFor(seed.citizen);
careerState(seed.citizen);stairState(seed.citizen);seed.stair=null;seed.shiftMoment=null;seed.neighborhoodNews=[];seed.community={};seed.alphaProgress=alphaProgress(seed.citizen);seed.equipment=equipmentSnapshot(seed.citizen,Object.entries(gearCatalog).map(([id,g])=>({id,stock:g.stock||0})),seed.world);seed.careers=careerSnapshot(seed.citizen,seed.world);seed.shiftTypes=shiftTypes;seed.loadoutEffects=gearEffects(seed.citizen);seed.jobs=Object.entries(jobs).map(([id,j])=>({id,...j,quotes:Object.keys(shiftTypes).map(mode=>jobQuote(seed.citizen,j,mode,seed.world))}));
const css=await readFile('public/style.css','utf8')+'\n'+await readFile('public/terminal.css','utf8')+'\n'+await readFile('public/occult.css','utf8')+'\n'+await readFile('public/noir.css','utf8')+'\n'+await readFile('public/residency.css','utf8')+'\n'+await readFile('public/street.css','utf8')+'\n'+await readFile('public/life.css','utf8')+'\n'+await readFile('public/home.css','utf8')+'\n'+await readFile('public/alpha.css','utf8');const app=(await readFile('public/app.js','utf8')).replace('/* RESIDENCY */',await readFile('public/residency.js','utf8')).replace('/* CHARACTER */',await readFile('public/character.js','utf8')).replace('/* STREET */',await readFile('public/street.js','utf8')).replace('/* LIFE */',await readFile('public/life.js','utf8')).replace('/* HOME */',await readFile('public/home.js','utf8')).replace('/* ALPHA */',await readFile('public/alpha.js','utf8')).replace('/* SEED */','const SEED='+JSON.stringify(seed)+';');
const page=(await readFile('public/index.html','utf8')).replace('/* STYLES */',css).replace('/* APP */',app);
const assets={};for(const name of ['city','factory','market','city-noir','citizen','scavenge','workshop','neural','registry','housing','transit','casino','portrait-kit','portrait-woman','portrait-man','portrait-nonbinary','portrait-cropped','portrait-swept','portrait-bob','portrait-braids','portrait-weathercoat','portrait-adminuniform','portrait-securityuniform','contact-neri','contact-esra','contact-voss','contact-rook','bunkhouse','barrel-fire'])assets['/art/'+name+'.webp']=(await readFile('public/'+name+'.webp')).toString('base64');
const living=(await readFile('worker/living.js','utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'');
const contacts=(await readFile('worker/contacts.js','utf8')).replace(/export /g,'');
const neighborhood=(await readFile('worker/neighborhood.js','utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'');
const community=(await readFile('worker/community.js','utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'');
const tenants=(await readFile('worker/tenants.js','utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'');
const aftermath=(await readFile('worker/aftermath.js','utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'');
const residency=(await readFile('worker/residency.js','utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'');
const street=(await readFile('worker/street.js','utf8')).replace(/export /g,'');
const life=(await readFile('worker/life.js','utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'');
const orders=(await readFile('worker/orders.js','utf8')).replace(/export /g,'');
const crises=(await readFile('worker/crises.js','utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'');
const citylife=(await readFile('worker/citylife.js','utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'');
const progression=(await readFile('worker/progression.js','utf8')).replace(/export /g,'');
const stories=(await readFile('worker/stories.js','utf8')).replace(/export /g,'');
const forces=(await readFile('worker/forces.js','utf8')).replace(/export /g,'');
const game=(await readFile('worker/game.js','utf8')).replace(/^import .*;\n/gm,'').replace(/export /g,'');const entry=(await readFile('worker/index.js','utf8')).replace(/^import .*;\n/gm,'');
await writeFile('dist/server/index.js',living+'\n'+contacts+'\n'+tenants+'\n'+neighborhood+'\n'+community+'\n'+aftermath+'\n'+residency+'\n'+street+'\n'+life+'\n'+orders+'\n'+crises+'\n'+citylife+'\n'+forces+'\n'+progression+'\n'+stories+'\n'+game+'\nconst page='+JSON.stringify(page)+';\nconst assets='+JSON.stringify(assets)+';\n'+entry);
await cp('.openai/hosting.json','dist/.openai/hosting.json');await cp('drizzle','dist/.openai/drizzle',{recursive:true});
console.log('Built SCHISM Worker, 29 original art assets, and D1 migrations.');
