import assert from 'node:assert/strict';
import {harness} from './test-harness.mjs';
import {resetCharacters,CHARACTER_RESET_ID} from '../worker/reset.js';
const h=harness(),db=h.db;let checks=0;
const check=(condition,label)=>{assert.ok(condition,label);checks++;};
const count=table=>db.sqlite.prepare(`SELECT count(*) n FROM ${table}`).get().n;
await h.fixture('old',{credits:9999,rep:100,shifts:100,health:100,energy:100,fullness:100,warmth:100,official:true,business:true,property:true,bread:2});
await h.fixture('other',{credits:222,energy:100,fullness:100,warmth:100});
const oldIds=(await h.read('old')).citizens.map(c=>c.id);
await h.action('old',{action:'post',body:'An old notice from an established citizen.'});
await h.action('old',{action:'list',id:'bread',price:4});
await h.action('old',{action:'work',id:'sorting'});
await h.start('other',{action:'work',id:'records'});
const worldBefore=(await h.read('old')).world,forceBefore=db.sqlite.prepare('SELECT * FROM forces').all(),projectBefore=db.sqlite.prepare('SELECT * FROM projects').all(),marketBefore=db.sqlite.prepare('SELECT * FROM market').all();
check(count('citizens')===2&&count('listings')===1&&count('posts')===1&&count('journal')>0,'Reset fixture includes established progress and linked records');
check(count('city_activity')===2,'Reset fixture includes completed and pending city contributions');
const result=await resetCharacters(db,h.now);
check(result.applied&&result.citizens===2&&result.id===CHARACTER_RESET_ID,'One reset receipt records the deleted citizen count');
check(count('citizens')===0,'All old citizen records are removed');
check(count('listings')===0,'Player listings and escrow from deleted citizens are removed');
check(count('posts')===0,'Old citizen notices are removed');
check(count('journal')===0,'Old personal journals are removed');
check(count('city_activity')===1&&db.sqlite.prepare('SELECT completes FROM city_activity').get().completes<=h.now,'Pending contributions are canceled while completed city history remains');
check(JSON.stringify(db.sqlite.prepare('SELECT * FROM market').all())===JSON.stringify(marketBefore),'Shared market is retained');
check(JSON.stringify(db.sqlite.prepare('SELECT * FROM forces').all())===JSON.stringify(forceBefore),'Shared faction history is retained');
check(JSON.stringify(db.sqlite.prepare('SELECT * FROM projects').all())===JSON.stringify(projectBefore),'Shared repair history is retained');
let s=await h.read('old');check(!s.citizen.registered&&s.citizen.credits===0&&s.citizen.shifts===0&&s.citizen.rep===0,'Same account returns to a fresh unregistered character');
check(!oldIds.includes(s.citizen.id)&&!s.citizen.official&&!s.citizen.business&&!s.citizen.property&&!s.citizen.activity,'Old character identity, institutions, and assignments cannot carry over');
check(s.world.day===worldBefore.day,'Reset never restarts the city clock');
await h.register('old','Fresh Arrival');s=await h.read('old');check(s.citizen.registered&&s.citizen.daysInCity===0&&s.citizen.alignment===0&&s.citizen.rentDebt===0,'Fresh registration receives neutral arrival conditions');
const freshId=s.citizen.id;await resetCharacters(db,h.now+1000);s=await h.read('old');check(s.citizen.id===freshId&&s.citizen.registered&&s.citizen.name==='Fresh Arrival','Retrying the reset never deletes a new character');
check(count('maintenance_runs')===1,'Reset completion marker is permanent and unique');
const concurrent=harness();await concurrent.fixture('first');await concurrent.fixture('second');const race=await Promise.all([resetCharacters(concurrent.db,concurrent.now),resetCharacters(concurrent.db,concurrent.now)]);
check(race.filter(r=>r.applied).length===1&&race.every(r=>r.citizens===2),'Concurrent reset requests apply once and return the same receipt');
const failure=harness();await failure.fixture('resident');failure.db.sqlite.exec("CREATE TRIGGER reject_reset BEFORE DELETE ON citizens BEGIN SELECT RAISE(ABORT,'reset failure'); END");
await assert.rejects(()=>resetCharacters(failure.db,failure.now),/reset failure/);checks++;
check(failure.db.sqlite.prepare('SELECT count(*) n FROM citizens').get().n===1&&failure.db.sqlite.prepare('SELECT count(*) n FROM maintenance_runs').get().n===0,'A failed reset preserves citizens and leaves no false receipt');
console.log(`Passed ${checks} reset checks: complete cleanup, fresh account registration, retained city state, retry/concurrency safety and transaction rollback.`);
