import assert from 'node:assert/strict';
import { snapshot,act,settle,initial,world } from '../worker/game.js';
import { localDB } from './local-db.mjs';
const db=localDB();let now=Date.UTC(2026,9,5,1);let checks=0;
const action=async(owner,input)=>{now+=1000;return act(db,owner,input,now);};
const read=owner=>snapshot(db,owner,now);
function check(condition,message){assert.ok(condition,message);checks++;}
async function fail(owner,input){await assert.rejects(()=>action(owner,input));checks++;}
const first=await read('alice');check(first.citizen.credits===9&&first.citizen.rentDebt===12,'Start three credits short');
await fail('alice',{action:'rent'});check((await read('alice')).citizen.credits===9,'Invalid rent does not change balance');
let result=await action('alice',{action:'work',id:'sorting'});check(result.citizen.credits===17&&result.citizen.energy===40&&result.citizen.rep===1,'Shift has expected costs and pay');
result=await action('alice',{action:'buy',id:'soup'});check(result.citizen.credits===12&&result.citizen.fullness===61,'Hot soup consumed immediately');
result=await action('alice',{action:'rent'});check(result.citizen.credits===0&&result.citizen.rentDebt===0,'Rent payment settles debt');
check((await read('alice')).citizen.credits===0,'Save persists across state requests');
await fail('alice',{action:'work',id:'maintenance'});await fail('alice',{action:'buy',id:'__proto__'});await fail('alice',{action:'work',id:'constructor'});
result=await action('alice',{action:'rest'});check(result.citizen.energy===88,'Rest restores energy');
const before=await read('alice');db.sqlite.prepare('UPDATE citizens SET data=? WHERE owner=?').run(JSON.stringify({...before.citizen,energy:1}), 'alice');
await fail('alice',{action:'work',id:'sorting'});check((await read('alice')).citizen.credits===0,'Insufficient-energy shift does not mint credits');
const offline=settle(initial(now),now+1000*60*60*80);check(offline.evicted&&offline.housing==='street'&&offline.rentDebt===48,'Offline rent accumulation triggers eviction');
const bob=await read('bob'),cara=await read('cara');check(bob.citizen.id!==cara.citizen.id,'Separate identities have separate citizens');
db.sqlite.prepare('UPDATE market SET stock=1 WHERE id=?').run('bread');now+=1000;
const stockRace=await Promise.allSettled([act(db,'bob',{action:'buy',id:'bread'},now),act(db,'cara',{action:'buy',id:'bread'},now)]);
check(stockRace.filter(r=>r.status==='fulfilled').length===1,'Exactly one buyer receives final stock');
check(db.sqlite.prepare('SELECT stock FROM market WHERE id=?').get('bread').stock===0,'Shared stock cannot become negative');
const winner=stockRace[0].status==='fulfilled'?'bob':'cara',loser=winner==='bob'?'cara':'bob';
check((await read(loser)).citizen.credits===9,'Failed stock purchase rolls back credits');
const sellerBefore=(await read(winner)).citizen.credits;
result=await action(winner,{action:'list',id:'bread',price:4});const offer=result.listings[0];
check(result.citizen.bread===0,'Listing escrows one item');
await fail(winner,{action:'trade',id:offer.id});await read('dana');now+=1000;
const tradeRace=await Promise.allSettled([act(db,loser,{action:'trade',id:offer.id},now),act(db,'dana',{action:'trade',id:offer.id},now)]);
check(tradeRace.filter(r=>r.status==='fulfilled').length===1,'A listing sells only once under concurrent buys');
check((await read(winner)).citizen.credits===sellerBefore+4,'Seller is credited exactly once');
check(db.sqlite.prepare('SELECT count(*) n FROM action_guards').get().n===0,'Transaction guards do not accumulate');
result=await action(winner,{action:'rename',name:'Mara Kess'});check(result.citizen.name==='Mara Kess','Citizen name saves');
result=await action(winner,{action:'post',body:'Looking for scrap. Fair prices.'});check((await read(loser)).board.some(p=>p.body==='Looking for scrap. Fair prices.'),'Noticeboard shared between citizens');
result=await action(winner,{action:'union'});check(result.citizen.union&&result.totals.members===1,'Union membership affects shared registry');
const old=await read(winner);db.sqlite.prepare('UPDATE citizens SET data=? WHERE owner=?').run(JSON.stringify({...old.citizen,credits:500,rep:25,energy:100,fullness:100,warmth:100,bread:3}),winner);
result=await action(winner,{action:'business'});check(result.citizen.business&&result.citizen.role==='Shop owner','Business license acquired');
result=await action(winner,{action:'business_work'});check(result.citizen.bread===2&&result.citizen.credits===417,'Shop session uses stock and generates sale');
result=await action(winner,{action:'property'});check(result.citizen.property,'Lease acquired');result=await action(winner,{action:'collect'});check(result.citizen.credits===246,'Lease income collected');await fail(winner,{action:'collect'});
result=await action(winner,{action:'official'});check(result.citizen.official,'Municipal post acquired');result=await action(winner,{action:'official_work'});check(result.citizen.credits===203,'Official shift pays salary');
check(world(now+21600000).day===world(now).day+1,'City clock advances while absent');
console.log(`Passed ${checks} gameplay checks: save, costs, rent, eviction, identity, concurrent stock/trades, union, business, property, and official work.`);
