import assert from 'node:assert/strict';
import {harness} from './test-harness.mjs';
import {startQuick,finishQuick,streetSnapshot} from '../worker/street.js';
import {initial,world} from '../worker/game.js';
import {residencyState,accrueTax} from '../worker/residency.js';
import {careerState} from '../worker/progression.js';
let checks=0;const check=(ok,label)=>{assert.ok(ok,label);checks++;};
const reject=async(fn,pattern)=>{await assert.rejects(fn,pattern);checks++;};
const h=harness();await h.register('mara','Mara Vale');let s=await h.read('mara');
check(Object.values(s.citizen.materials).every(n=>n===0)&&s.streetLife.used===0,'Fresh citizens have no scavenged resources or spent short-task quota');
s=await h.start('mara',{action:'quick',id:'bins'});const binDeadline=s.citizen.errand.endsAt;
check(s.citizen.energy<53&&s.citizen.credits===0,'Scavenging reserves energy immediately without instant money');
check(Object.values(s.citizen.materials).every(n=>n===0),'Scavenged rewards are unavailable before the deadline');
check(s.jobs.every(j=>j.quotes.every(q=>q.blocked==='Finish your short task.')),'Job offers explain the active short-task restriction');
await reject(()=>h.start('mara',{action:'quick',id:'decode'}),/Finish your current short task/);
await reject(()=>h.start('mara',{action:'work',id:'sorting'}),/Finish your short task/);
h.now=binDeadline-1;s=await h.read('mara');check(!!s.citizen.errand,'One millisecond before completion is still pending');h.now=binDeadline;
const race=await Promise.all([h.read('mara'),h.read('mara')]);check(race.every(s=>!s.citizen.errand&&Object.values(s.citizen.materials).reduce((a,b)=>a+b,0)===2),'Concurrent reads credit scavenged rewards exactly once');
check(h.db.sqlite.prepare('SELECT count(*) n FROM journal WHERE created=?').get(binDeadline).n===1,'Concurrent completion creates one journal receipt');
await h.patch('mara',{materials:{cloth:4,wire:4,circuit:2,data:2},energy:100});
s=await h.start('mara',{action:'craft',id:'heatpack'});check(s.citizen.materials.cloth===2&&s.citizen.materials.wire===3&&s.citizen.heatpack===0,'Craft costs are reserved without awarding the item early');
h.now=s.citizen.errand.endsAt;s=await h.read('mara');check(s.citizen.heatpack===1&&s.citizen.workshopXP===1,'Completed craft awards one supply and separate workshop XP');
const warmth=s.citizen.warmth;s=await h.start('mara',{action:'use_craft',id:'heatpack'});check(s.citizen.heatpack===0&&s.citizen.warmth>warmth+13,'Crafted warming supply is usable exactly once');
await reject(()=>h.start('mara',{action:'use_craft',id:'heatpack'}),/do not have/);
await h.patch('mara',{materials:{cloth:0,wire:0,circuit:0,data:0}});await reject(()=>h.start('mara',{action:'craft',id:'scrap'}),/Missing materials/);
await reject(()=>h.start('mara',{action:'craft',id:'__proto__'}),/published recipe/);
await h.patch('mara',{energy:100,materials:{cloth:4,wire:4,circuit:2,data:2}});
s=await h.start('mara',{action:'work',id:'sorting'});const shiftEnds=s.citizen.activity.endsAt,creditsBefore=s.citizen.credits;
s=await h.start('mara',{action:'quick',id:'decode'});check(s.citizen.activity&&s.citizen.errand&&s.citizen.errand.endsAt<shiftEnds,'Break task coexists with a long paid shift');
h.now=s.citizen.errand.endsAt;s=await h.read('mara');check(!s.citizen.errand&&s.citizen.activity&&s.citizen.materials.data===3&&s.citizen.credits===creditsBefore,'Short completion preserves the pending shift and its deferred wages');
await reject(()=>h.start('mara',{action:'quick',id:'bins'}),/shift is over/);
s=await h.start('mara',{action:'craft',id:'bandage'});h.now=s.citizen.errand.endsAt;s=await h.read('mara');check(s.citizen.bandage===1&&s.citizen.activity,'Crafting works during a break without canceling work');
h.now=shiftEnds;s=await h.read('mara');check(!s.citizen.activity&&s.citizen.credits>creditsBefore&&s.citizen.bandage===1,'Shift completion preserves supplies made on a break');
await h.patch('mara',{energy:100,street:{day:s.world.day,count:0,games:0,leads:[]}});
s=await h.start('mara',{action:'network_job',id:'public'});const leadEnds=s.citizen.errand.endsAt;check(s.citizen.materials.data===2&&s.citizen.street.leads.includes('public'),'Network acceptance reserves trace and daily contract slot');
check((await h.read('neighbor')).cityLife.metrics.freight===0,'Pending contract does not affect district freight early');
h.now=leadEnds;const other=await h.read('neighbor');check(other.cityLife.metrics.freight===1,'Another citizen sees completed freight without owner settlement');
s=await h.read('mara');check(s.citizen.taxEarned>0&&s.citizen.rep>=2,'Public network pay is taxed and earns declared trust');
await reject(()=>h.start('mara',{action:'network_job',id:'public'}),/already accepted/);
s=await h.start('mara',{action:'network_job',id:'wound'});const gross=s.citizen.taxEarned;h.now=s.citizen.errand.endsAt;s=await h.read('mara');check(s.citizen.taxEarned===gross&&s.citizen.heat>3&&s.citizen.alignment<0,'Hidden network money remains unreported and draws heat/Chaos');
check((await h.read('neighbor')).cityLife.metrics.crime===1,'Hidden network delivery contributes to shared criminal pressure');
await h.patch('mara',{energy:100,street:{day:s.world.day,count:10,games:0,leads:[]}});await reject(()=>h.start('mara',{action:'quick',id:'sweep'}),/Ten short tasks/);
h.now+=21600000;s=await h.read('mara');check(s.streetLife.used===0,'Daily short-task quota resets on the shared cycle');
await h.patch('mara',{energy:1});await reject(()=>h.start('mara',{action:'quick',id:'decode'}),/Need 7 energy/);
await h.patch('mara',{energy:100,detainedUntil:h.now+60000});await reject(()=>h.start('mara',{action:'quick',id:'bins'}),/sentence/);
await h.patch('mara',{detainedUntil:0});await h.start('mara',{action:'rest'});await reject(()=>h.start('mara',{action:'quick',id:'decode'}),/full attention/);
const gambling=()=>{const p=residencyState(careerState({...initial(h.now),registered:true,credits:10,energy:100}),h.now);streetSnapshot(p,world(h.now));return p;};
let p=gambling();startQuick(p,{action:'casino',bet:3},world(h.now),.44);check(p.credits===7&&p.energy===94,'Casino reserves stake and energy');finishQuick(p,h.now+20000,accrueTax);check(p.credits===13,'Winning payout includes the reserved stake and declared profit');finishQuick(p,h.now+30000,accrueTax);check(p.credits===13,'Winning hand cannot pay twice');
p=gambling();startQuick(p,{action:'casino',bet:3},world(h.now),.45);finishQuick(p,h.now+20000,accrueTax);check(p.credits===7,'Losing hand keeps the stake and pays nothing');
for(const bet of [-1,0,4,1.5,'3',Infinity]){assert.throws(()=>startQuick(gambling(),{action:'casino',bet},world(h.now),0),/Stake/);checks++;}
p=gambling();p.street.games=4;assert.throws(()=>startQuick(p,{action:'casino',bet:1},world(h.now),0),/Four hands/);checks++;
const chat=harness();await chat.register('a','One Speaker');await chat.register('b','Other Listener');s=await chat.start('a',{action:'network_post',channel:'district',body:'<img src=x onerror=alert(1)> literal text'});const b=await chat.read('b');check(b.network[0].name==='One Speaker'&&b.network[0].body.startsWith('<img'),'Shared network attaches authoritative character name and preserves literal text for escaped display');
await reject(()=>chat.start('a',{action:'network_post',channel:'exchange',body:'Too soon'}),/15 seconds/);chat.now+=16000;
await reject(()=>chat.start('a',{action:'network_post',channel:'__proto__',body:'x'}),/channel/);
await reject(()=>chat.start('a',{action:'network_post',channel:'district',body:'x'.repeat(321)}),/1–320/);
await chat.start('a',{action:'network_post',channel:'exchange',body:'Wanted: two fabric strips.'});check((await chat.read('b')).network.some(m=>m.channel==='exchange'),'Messages retain their selected channel');
chat.now+=16000;await chat.patch('a',{detainedUntil:chat.now+60000,bandage:1,health:40});s=await chat.start('a',{action:'network_post',channel:'district',body:'Speaking from detention.'});check(s.network.some(m=>m.body==='Speaking from detention.'),'Detention allows communication while blocking field tasks');s=await chat.start('a',{action:'use_craft',id:'bandage'});check(s.citizen.bandage===0&&s.citizen.health>49,'Detained citizens can use crafted medical supplies');
const legacy=gambling();legacy.official=true;legacy.security=true;careerState(legacy);check(legacy.ownedGear.includes('adminuniform')&&legacy.ownedGear.includes('securityuniform'),'Existing earned institutions receive corresponding wardrobe pieces');
const uniforms=harness();await uniforms.fixture('official',{joined:uniforms.now-3*86400000,rep:100,credits:100,careers:{civic:{xp:100,shifts:20}},heat:0});s=await uniforms.start('official',{action:'official'});check(s.citizen.loadout.body==='adminuniform'&&s.citizen.ownedGear.includes('adminuniform'),'Administration appointment awards and equips the visible uniform');
await reject(()=>uniforms.start('official',{action:'gear_buy',id:'securityuniform'}),/not for sale/);
const together=harness();await together.fixture('worker',{energy:100,fullness:100,warmth:100});s=await together.start('worker',{action:'work',id:'sorting'});const boundary=s.citizen.activity.endsAt;together.now=boundary-21000;s=await together.start('worker',{action:'quick',id:'sweep'});together.now=Math.max(boundary,s.citizen.errand.endsAt);s=await together.read('worker');check(!s.citizen.activity&&!s.citizen.errand&&s.citizen.credits===18,'Coincident shift and short-task completions apply both rewards atomically');
check(together.db.sqlite.prepare('SELECT count(*) n FROM journal WHERE created=?').get(boundary).n===2,'Coincident completion retains both journal entries');
console.log(`Passed ${checks} street checks: concurrent timers, break restrictions, materials/crafting, tax, district contributions, casino limits, chat identity/rate limits, and earned uniforms.`);
