import assert from 'node:assert/strict';
import {harness} from './test-harness.mjs';
import {initial,settle,world,act} from '../worker/game.js';
const h=harness(),{db,read,fixture,patch,start,finish,action}=h;let checks=0;
const check=(condition,label)=>{assert.ok(condition,label);checks++;};
const fail=async(owner,input)=>{await assert.rejects(()=>start(owner,input));checks++;};
const first=await read('alice');check(!first.citizen.registered&&first.citizen.credits===0,'Account waits for character registration with no credits');
await fail('alice',{action:'work',id:'sorting'});await h.register('alice','Mara Kess');
await fail('alice',{action:'register',name:'Second person',appearance:first.citizen.appearance});
let s=await start('alice',{action:'work',id:'sorting'});check(s.citizen.credits===0&&s.citizen.shifts===0&&s.citizen.activity.hours===2,'Work defers wages and shifts until completion');
check(s.citizen.energy<41&&s.citizen.energy>=40,'Work reserves energy at the start');await fail('alice',{action:'work',id:'sorting'});await fail('alice',{action:'rest'});
s=await finish('alice');check(s.citizen.credits===8&&s.citizen.rep===1&&s.citizen.shifts===1,'Completion awards declared pay and trust');
check(s.citizen.careers.mnemonic.xp===4,'Completion records career XP');
s=await action('alice',{action:'buy',id:'soup'});check(s.citizen.credits===3&&s.citizen.fullness>72,'Broth is consumed immediately');
check((await read('alice')).citizen.credits===3,'Save persists');
await fail('alice',{action:'work',id:'maintenance'});await fail('alice',{action:'buy',id:'__proto__'});await fail('alice',{action:'work',id:'constructor'});
const before=(await read('alice')).citizen.energy;s=await start('alice',{action:'rest'});check(s.citizen.energy<before+1,'Sleep never grants instant energy');s=await finish('alice');check(s.citizen.energy>before+37,'Free bunk sleep restores its smaller energy allowance over real time');await fail('alice',{action:'rest'});
await patch('alice',{energy:1});await fail('alice',{action:'work',id:'sorting'});check((await read('alice')).citizen.credits===3,'Invalid work cannot mint credits');
const offline=settle({...initial(h.now),registered:true},h.now+80*3600000);check(!offline.evicted&&offline.housing==='bunk'&&offline.rentDebt===0,'Offline free-bunk residence accumulates no rent debt');
await fixture('bob');await fixture('cara');check((await read('bob')).citizen.id!==(await read('cara')).citizen.id,'Account identities remain separate');
db.sqlite.prepare('UPDATE market SET stock=1 WHERE id=?').run('bread');h.now+=1000;
const race=await Promise.allSettled([act(db,'bob',{action:'buy',id:'bread'},h.now),act(db,'cara',{action:'buy',id:'bread'},h.now)]);check(race.filter(r=>r.status==='fulfilled').length===1,'Final shared ration is sold once');check(db.sqlite.prepare('SELECT stock FROM market WHERE id=?').get('bread').stock===0,'Stock remains nonnegative');
const winner=race[0].status==='fulfilled'?'bob':'cara',loser=winner==='bob'?'cara':'bob';check((await read(loser)).citizen.credits===9,'Failed purchase rolls back credits');
const balance=(await read(winner)).citizen.credits;s=await action(winner,{action:'list',id:'bread',price:9});const listing=s.listings[0];check(s.citizen.bread===0,'Listing escrows its item');await fail(winner,{action:'trade',id:listing.id});
await fixture('dana');h.now+=1000;const trades=await Promise.allSettled([act(db,loser,{action:'trade',id:listing.id},h.now),act(db,'dana',{action:'trade',id:listing.id},h.now)]);check(trades.filter(r=>r.status==='fulfilled').length===1,'Player listing sells once');s=await read(winner);check(s.citizen.credits===balance+9&&s.citizen.taxDebt===1,'Seller gets payment and owes tax exactly once');
await action(winner,{action:'post',body:'Looking for factory work.'});check((await read(loser)).board.some(p=>p.body==='Looking for factory work.'),'Noticeboard is shared');
await action(winner,{action:'rename',name:'Iona Vale'});check((await read(winner)).citizen.name==='Iona Vale','Name persists');
await patch(winner,{credits:500,rep:30,energy:100,health:100,fullness:100,warmth:100,bread:3,joined:h.now-3*86400000,careers:{mnemonic:{xp:0,shifts:0},transit:{xp:0,shifts:0},civic:{xp:80,shifts:20},recovery:{xp:0,shifts:0}}});
s=await action(winner,{action:'union'});check(s.citizen.union&&s.totals.members===1,'Union is persistent and counted');
s=await action(winner,{action:'business'});check(s.citizen.business,'Trading license can be earned');const shopBefore=s.citizen.credits;s=await start(winner,{action:'business_work'});check(s.citizen.credits===shopBefore&&s.citizen.bread===2,'Shop reserves stock and defers earnings');s=await finish(winner);check(s.citizen.credits===shopBefore+7,'Shop earns quoted payment');
s=await action(winner,{action:'property'});check(s.citizen.property,'Property lease persists');const leaseBefore=s.citizen.credits;s=await action(winner,{action:'collect'});check(s.citizen.credits===leaseBefore+9,'Lease pays once per city day');await fail(winner,{action:'collect'});
s=await action(winner,{action:'official'});check(s.citizen.official,'Trained established citizen can enter administration');const officialBefore=s.citizen.credits;s=await action(winner,{action:'official_work'});check(s.citizen.credits===officialBefore+17,'Administrative work pays at completion');
check(world(h.now+21600000).day===world(h.now).day+1,'Shared clock advances without actions');check(db.sqlite.prepare('SELECT count(*) n FROM action_guards').get().n===0,'Transaction guards do not accumulate');
console.log(`Passed ${checks} gameplay checks: accounts, timed work/sleep, offline survival, shared-stock/trade races, income tax, institutions and persistence.`);
