import assert from 'node:assert/strict';
import { snapshot,act } from '../worker/game.js';
import { harness } from './test-harness.mjs';
const h=harness(),db=h.db;let checks=0;
const read=async owner=>{await h.fixture(owner);return h.read(owner);};
const action=async(owner,input)=>{await h.fixture(owner);return h.action(owner,input);};
const pick=(owner,id,node,choice)=>action(owner,{action:'encounter',id,node,choice});
const check=(condition,label)=>{assert.ok(condition,label);checks++;};
const reject=async operation=>{await assert.rejects(operation);checks++;};
const first=await read('solo');check(first.encounters.find(x=>x.id==='neighbor').choices.length===3,'Personal story available from the first day');
check(first.encounters.find(x=>x.id==='wages').locked,'Factory story waits for work');
check(first.encounters.find(x=>x.id==='neighbor').choices[0].blocked,'Bread choice requires bread');
await reject(()=>pick('solo','neighbor','start','bread'));check((await read('solo')).citizen.story.decisions.length===0,'Unavailable choice does not change history');
let result=await pick('solo','neighbor','start','blanket');check(result.citizen.credits===3&&result.citizen.story.contacts.iona===2&&result.citizen.story.threads.neighbor==='return','Choice applies costs, relationship, and branch');
check(result.encounters.find(x=>x.id==='neighbor').locked,'Follow-up waits for two shifts');
await reject(()=>pick('solo','neighbor','start','blanket'));check((await read('solo')).citizen.credits===3,'A prior choice cannot be replayed');
await reject(()=>pick('solo','neighbor','return','care'));
await action('solo',{action:'work',id:'sorting'});await action('solo',{action:'work',id:'sorting'});
result=await pick('solo','neighbor','return','care');check(result.citizen.story.threads.neighbor==='done'&&result.citizen.story.contacts.iona===3,'Follow-up resolves and keeps relationship');
const saved=await read('solo');check(saved.citizen.story.decisions.length===2,'Choices persist when the citizen is read again');
const other=await read('other');check(other.citizen.story.decisions.length===0&&other.citizen.story.threads.neighbor===undefined,'Other citizens do not inherit your story');
result=await pick('other','neighbor','start','leave');check(result.citizen.story.threads.neighbor==='distance','A different choice reaches a different chapter');
await reject(()=>pick('other','neighbor','return','care'));
result=await pick('other','neighbor','distance','alone');check(result.citizen.story.flags.alone&&result.citizen.story.contacts.iona===-1,'Other branch has different lasting flags and relationship');
result=await pick('solo','wages','start','challenge');check(result.citizen.story.threads.wages==='ledger'&&result.citizen.story.contacts.havel===-2,'Wage challenge changes future encounter');
await reject(()=>pick('solo','wages','ledger','union'));await action('solo',{action:'union'});
result=await pick('solo','wages','ledger','union');check(result.citizen.story.flags.exposedWages,'Union affiliation opens a personal choice');
const deep=JSON.parse(JSON.stringify(result.citizen));db.sqlite.prepare('UPDATE citizens SET data=? WHERE owner=?').run(JSON.stringify({...deep,scrap:12,energy:100,warmth:80,health:100,fullness:100}),'solo');
const contributor=await read('other');db.sqlite.prepare('UPDATE citizens SET data=? WHERE owner=?').run(JSON.stringify({...contributor.citizen,scrap:1,energy:100,warmth:80,health:100,fullness:100}),'other');
for(let i=0;i<11;i++)await action('solo',{action:'contribute'});
check((await read('other')).project.progress===11,'City repair progress visible to a different player');
h.now+=1000;const race=await Promise.allSettled([act(db,'solo',{action:'contribute'},h.now),act(db,'other',{action:'contribute'},h.now)]);
check(race.filter(r=>r.status==='fulfilled').length===1,'Only one player can donate the final part');
result=await read('other');check(result.project.progress===12&&result.world.heating,'Shared repair activates district heating for all players');
check(db.sqlite.prepare('SELECT count(*) n FROM action_guards').get().n===0,'Project guards are cleaned up');
const warmth=result.citizen.warmth;result=await action('other',{action:'work',id:'cleaning'});check(Math.abs(result.citizen.warmth-(warmth-(2+result.world.coldModifier)))<.01,'Completed shared project reduces working cold exposure');
await reject(()=>action('solo',{action:'contribute'}));
const beforeReset=await read('other');h.now+=21600000;const reset=await read('other');check(reset.project.progress===0&&!reset.world.heating&&reset.project.day===beforeReset.project.day+1,'A new city day starts a new shared repair');
await reject(()=>pick('other','__proto__','start','bread'));
console.log(`Passed ${checks} narrative/multiplayer checks: branching, costs, replay protection, private history, gated choices, concurrent district repairs, shared perks, and world reset.`);
