import assert from 'node:assert/strict';
import {harness} from './test-harness.mjs';
import {act,initial,settle,world} from '../worker/game.js';
import {tenantMembership} from '../worker/tenants.js';
import {CITY_DAY_MS} from '../worker/residency.js';
let checks=0;const check=(ok,label)=>{assert.ok(ok,label);checks++;},reject=async(fn,re)=>{await assert.rejects(fn,re);checks++;};
const quickEnd=async(h,o)=>{const s=await h.read(o);h.now=s.citizen.errand.endsAt;return h.read(o);};
{
 const h=harness();await h.register('absent');const id=(await h.read('absent')).citizen.id;h.now+=10*86400000;let s=await h.read('absent');check(s.citizen.id===id&&s.citizen.housing==='bunk'&&!s.citizen.evicted&&s.citizen.rentDebt===0,'Ten-day absence retains a free basic bunk without rent debt');check(s.citizen.health===10&&s.citizen.energy===100,'Exposure remains harsh but bounded and idle recovery survives absence');
 const afterRelief=await h.start('absent',{action:'relief'});s=await h.start('absent',{action:'warm_fire'});check(s.citizen.energy>=20&&s.citizen.warmth<=afterRelief.citizen.warmth,'Barrel fire gives no immediate warmth or energy grant');s=await quickEnd(h,'absent');check(s.citizen.warmth>20,'A real barrel task restores limited warmth');await reject(()=>h.start('absent',{action:'warm_fire'}),/One warm/);s=await h.start('absent',{action:'work',id:'cleaning'});check(!!s.citizen.activity,'An absent broke citizen can return to paid work using ordinary relief');
 const legacy=settle({...initial(h.now),registered:true,housing:'street',evicted:true,rentDebt:48,rentCycles:4},h.now);check(legacy.housing==='bunk'&&legacy.rentDebt===0&&legacy.housingReform.waived===48,'Old free-bunk eviction and arrears are waived once');const privateLegacy=settle({...initial(h.now),registered:true,housing:'street',evicted:true,rentDebt:80,rentCycles:4},h.now);check(privateLegacy.rentDebt===80&&privateLegacy.housing==='street','Legacy private-room arrears are retained');
}
{
 const h=harness();await h.fixture('sleeper',{credits:0,energy:5,health:70,fullness:100,warmth:70});let s=await h.start('sleeper',{action:'rest'}),warm=s.citizen.warmth;check(Math.abs(s.citizen.energy-5)<.01&&s.citizen.activity.endsAt-h.now===5400000,'Free sleep reserves the real ninety-minute assignment');s=await h.finish('sleeper');check(Math.abs(s.citizen.energy-43)<.01&&s.citizen.warmth<warm&&s.citizen.credits===0,'Free bunks restore thirty-eight energy and no warmth for no credits');await reject(()=>h.start('sleeper',{action:'rest'}),/One full/);
 const other=harness();await other.fixture('street',{credits:0,energy:5,health:70,fullness:100,warmth:70,housing:'street',housingVersion:1,rentDebt:0,rentCycles:0});await other.start('street',{action:'rest'});s=await other.finish('street');check(Math.abs(s.citizen.energy-35)<.01,'Cardboard sleep restores less energy than the bunkhouse');
}
{
 const h=harness();await h.fixture('tenant',{credits:500,energy:100,health:100,fullness:100,warmth:100,rentDebt:0,rentCycles:0});let s=await h.start('tenant',{action:'upgrade'});check(s.citizen.credits===455&&s.living.current.rent===20,'Private-room deposit and ongoing rent remain distinct');s=await h.start('tenant',{action:'rent_prepay',cycles:2});check(s.citizen.credits===415&&s.citizen.finance.rentReserve===40,'Prepayment holds actual spendable money');await reject(()=>h.start('tenant',{action:'rent_prepay',cycles:1.5}),/1–8/);await reject(()=>h.start('tenant',{action:'rent_prepay',cycles:9}),/1–8/);
 const due=s.citizen.nextRentAt;h.now=due+CITY_DAY_MS;const reads=await Promise.all([h.read('tenant'),h.read('tenant')]);check(reads.every(x=>x.citizen.finance.rentReserve===0&&x.citizen.rentDebt===0&&x.citizen.finance.rentPaid===40),'Concurrent offline settlement consumes prepaid bills exactly once');h.now=due+10*CITY_DAY_MS;s=await h.read('tenant');check(s.citizen.rentDebt===80&&s.citizen.evicted&&s.citizen.housing==='street','An absent private tenant owes at most four bills');s=await h.start('tenant',{action:'return_bunk'});check(s.citizen.housing==='bunk'&&!s.citizen.evicted&&s.citizen.rentDebt===80,'Free recovery remains accessible without erasing private arrears');await reject(()=>h.start('tenant',{action:'upgrade'}),/arrears/);h.now+=20*CITY_DAY_MS;s=await h.read('tenant');check(s.citizen.rentDebt===80,'Returning to a free bunk adds no further private-housing debt');await h.start('tenant',{action:'rent'});check((await h.read('tenant')).citizen.rentDebt===0,'Earned funds can settle capped private arrears');await reject(()=>h.start('tenant',{action:'rent_prepay',cycles:1}),/no rent/);
 await h.fixture('refund',{credits:100,housing:'room',rentDebt:0,rentCycles:0});await h.start('refund',{action:'rent_prepay',cycles:2});s=await h.start('refund',{action:'return_bunk'});check(s.citizen.credits===100&&s.citizen.finance.rentReserve===0,'Leaving paid housing refunds only unused reserves');await reject(()=>h.start('refund',{action:'rent_reclaim'}),/no unused/);
}
{
 const h=harness();await h.fixture('seller',{credits:0,bread:2,energy:100,fullness:100,warmth:100});await h.fixture('buyer',{credits:100});let s=await h.start('seller',{action:'tax_reserve',enabled:true});check(s.citizen.finance.taxAuto&&s.citizen.credits===0,'Tax reserve can be enabled while broke');await reject(()=>h.start('seller',{action:'tax_reserve',enabled:'true'}),/whether/);s=await h.start('seller',{action:'list',id:'bread',price:10});const offer=s.listings.find(x=>x.seller===s.citizen.id);await h.start('seller',{action:'work',id:'cleaning'});await h.start('buyer',{action:'trade',id:offer.id});s=await h.read('seller');check(s.citizen.credits===9&&s.citizen.finance.taxReserve===1&&s.citizen.taxDebt===1,'Incoming listing income atomically reserves tax during a shift');s=await h.finish('seller');check(s.citizen.credits===14&&s.citizen.finance.taxReserve===1,'Shift settlement preserves incoming payment and finance reserves');h.now=s.citizen.taxDeadline;s=await h.read('seller');check(s.citizen.taxDebt===0&&s.citizen.taxPaid===1&&s.citizen.finance.taxReserve===0&&!s.citizen.taxHold,'Reserved tax pays at the offline deadline');check(s.citizen.taxRemainder===80,'Fractional tax survives automatic payment');
 s=await h.start('seller',{action:'tax_reserve',enabled:false});check(s.citizen.credits===14&&!s.citizen.finance.taxAuto,'Disabling an empty reserve cannot create money');await h.patch('seller',{taxDebt:3,taxHold:true,credits:5});await h.start('seller',{action:'tax_reserve',enabled:true});s=await h.read('seller');check(s.citizen.finance.taxReserve===3&&s.citizen.credits===2,'Enabling funds existing debt from real spendable credits');s=await h.start('seller',{action:'tax'});check(s.citizen.credits===2&&s.citizen.taxDebt===0&&s.citizen.taxHold,'Manual payment can use reserves without clearing an ID hold');
 await h.patch('seller',{taxDebt:2,credits:5});await h.start('seller',{action:'tax_reserve',enabled:true});s=await h.start('seller',{action:'tax_reserve',enabled:false});check(s.citizen.credits===5&&s.citizen.finance.taxReserve===0&&s.citizen.taxDebt===2,'Disabling refunds reserves while keeping the tax obligation');
}
{
 const h=harness();for(const o of ['a','b','outsider'])await h.fixture(o,{credits:0,energy:100,health:100,fullness:100,warmth:100,materials:{wire:10,cloth:10},bread:2,bandage:1});let s=await h.start('a',{action:'tenant_create',name:'North Stair'}),block=s.tenants.block.id;check(s.citizen.credits===0&&s.tenants.members.length===1,'A broke citizen can create a real association');await reject(()=>h.start('a',{action:'tenant_create',name:'Duplicate'}),/Leave/);await h.start('b',{action:'tenant_join',id:block});s=await h.start('a',{action:'tenant_post',body:'Copper for the draught line.'});check((await h.read('b')).tenants.messages.some(x=>x.body==='Copper for the draught line.'),'Building messages are shared with current members');check(!(await h.read('outsider')).tenants.messages,'Outsiders receive no private building channel');await reject(()=>h.start('outsider',{action:'tenant_take',item:'bread'}),/Join/);await reject(()=>h.start('a',{action:'tenant_post',body:'Again'}),/fifteen/);
 await h.start('a',{action:'tenant_donate',item:'wire',quantity:5});s=await h.start('a',{action:'tenant_donate',item:'cloth',quantity:5});check(s.citizen.materials.wire===5&&s.tenants.block.stock.wire===5,'Donations conserve owned goods and shared stock');await h.start('b',{action:'tenant_donate',item:'wire',quantity:1});await h.start('b',{action:'tenant_donate',item:'cloth',quantity:1});await h.start('a',{action:'tenant_donate',item:'bread',quantity:1});
 h.now+=1000;const race=await Promise.allSettled([act(h.db,'a',{action:'tenant_take',item:'bread'},h.now),act(h.db,'b',{action:'tenant_take',item:'bread'},h.now)]);check(race.filter(x=>x.status==='fulfilled').length===1,'The final donated ration is withdrawn once');s=await h.read('a');const sb=await h.read('b');check(s.tenants.block.stock.bread===0&&s.citizen.bread+sb.citizen.bread===4,'Withdrawal race conserves the shared ration');const taker=race[0].status==='fulfilled'?'a':'b';await h.start(taker,{action:'tenant_leave'});await h.start(taker,{action:'tenant_join',id:block});await reject(()=>h.start(taker,{action:'tenant_take',item:'bandage'}),/One relief/);await reject(()=>h.start('a',{action:'tenant_donate',item:'wire',quantity:-1}),/1–5/);await reject(()=>h.start('a',{action:'tenant_take',item:'wire'}),/consumables/);
 for(let i=0;i<6;i++){const o=i%2?'a':'b';s=await h.start(o,{action:'tenant_repair'});check(s.tenants.block.progress===i,'Assigned building work gives no early protection');if(i===5){const observer=await h.read('outsider');check(!observer.tenants.block,'The outsider remains outside the association');h.now=s.citizen.errand.endsAt;s=await h.read('a');}else s=await quickEnd(h,o);}
 check(s.tenants.block.progress===6&&s.tenants.block.stock.wire===0&&s.tenants.block.stock.cloth===0&&s.tenants.block.heatUntil>h.now,'Six completed repairs consume supplies and protect the building');await reject(()=>h.start('a',{action:'tenant_repair'}),/holding/);const end=s.tenants.block.heatUntil;h.now=end+1;s=await h.read('a');check(s.tenants.block.progress===0&&s.tenants.block.reserved===0&&s.tenants.block.round===2,'Protection expires into a new maintenance round without refilling supplies');const pastProtection=await tenantMembership(h.db,s.citizen.id,h.now);check(pastProtection.heatWindows.some(r=>r.until===end),'Expired completed repairs retain their exact historical window for offline settlement');check(h.db.sqlite.prepare('SELECT count(*) n FROM action_guards').get().n===0,'Building transaction guards are cleaned up');
}
{
 const pending=harness();await pending.fixture('pendingNeri',{district:{day:1,threads:{ration:{node:'neighbor',readyAt:pending.now,choices:['return']}},contacts:{neri:2},flags:{},decisions:[],cases:{},surveys:[],caseCount:{},responses:0,municipalSales:0}});check(!(await pending.read('pendingNeri')).districtLife.encounters.some(x=>x.id.startsWith('blanket_round-')),'Recurring check-ins wait for the contact’s unfinished original reply');let continued=await pending.start('pendingNeri',{action:'district_choice',id:'ration',node:'neighbor',choice:'visit'});check(continued.districtLife.encounters.some(x=>x.id==='neri_return'),'Finishing the original reply leaves today’s offer for its remembered continuation');
 const h=harness();await h.fixture('neriFriend',{district:{day:1,threads:{ration:{node:'done',choices:['return']}},contacts:{neri:3},flags:{},decisions:[],cases:{},surveys:[],caseCount:{},responses:0,municipalSales:0},materials:{cloth:2},energy:0});let s=await h.read('neriFriend'),entry=s.districtLife.encounters.find(x=>x.id==='neri_return');check(!!entry,'Returning a ration card selects the relationship-specific continuation');s=await h.start('neriFriend',{action:'district_choice',id:entry.id,node:'found',choice:'learn'});check(s.citizen.district.flags.mendingLesson&&s.citizen.energy<1,'An exhausted player can learn from an established contact');await reject(()=>h.start('neriFriend',{action:'district_choice',id:entry.id,node:'follow',choice:'answer'}),/reply/);h.now+=60000;s=await h.start('neriFriend',{action:'district_choice',id:entry.id,node:'follow',choice:'answer'});check(s.citizen.district.threads[entry.id].node==='done','A real later reply closes the remembered continuation');check(s.districtLife.encounters.filter(x=>x.id==='neri_return').length===0,'Continuation replies cannot reroll finished history');
 await h.fixture('broker',{district:{day:1,threads:{ration:{node:'done',choices:['sell']}},contacts:{neri:-1},flags:{},decisions:[],cases:{},surveys:[],caseCount:{},responses:0,municipalSales:0}});s=await h.read('broker');check(s.districtLife.encounters.some(x=>x.id==='neri_sale')&&!s.districtLife.encounters.some(x=>x.id==='neri_return'),'Selling the same card produces a different remembered response');h.now+=CITY_DAY_MS;s=await h.read('neriFriend');check(s.districtLife.encounters.some(x=>x.id.startsWith('blanket_round-')),'Known contacts offer a bounded recurring check-in next cycle');
 await h.fixture('mender',{energy:100,fullness:100,warmth:100,clothingWear:60,materials:{cloth:2}});await h.start('mender',{action:'mend_clothes'});s=await quickEnd(h,'mender');check(s.citizen.clothingWear===20&&s.citizen.materials.cloth===1,'Mending consumes owned fabric and reduces cosmetic wear at completion');
}
{
 const h=harness();await h.fixture('watcher');let s=await h.read('watcher'),crisis=s.cityLife.crisis.current;h.now=crisis.deadline;s=await h.read('watcher');check(s.cityLife.aftermath.paper[0].record.outcome==='failed','The newspaper stores the observed deadline outcome');const news=s.cityLife.aftermath.paper[0].body;h.now=crisis.started+CITY_DAY_MS+1000;s=await h.read('watcher');check(s.cityLife.aftermath.incidents.some(x=>x.id===crisis.id&&!x.recovered)&&s.world.coldModifier===1.5,'Failed boiler damage reaches the next cycle');
 await h.fixture('repairer',{energy:100,fullness:100,warmth:100,materials:{wire:6,data:6},credits:0});let task=s.cityLife.aftermath.incidents.find(x=>x.id===crisis.id);s=await h.start('repairer',{action:'recovery_work',id:task.id});check(s.citizen.materials.wire===5&&s.citizen.credits===0&&s.cityLife.aftermath.incidents.find(x=>x.id===task.id).completed===0,'Recovery consumes supplies while withholding payment and completed units');s=await quickEnd(h,'repairer');check(s.citizen.credits===2&&s.citizen.taxEarned===2,'Recovery pays taxable income at completion');await h.start('repairer',{action:'recovery_work',id:task.id});await quickEnd(h,'repairer');await reject(()=>h.start('repairer',{action:'recovery_work',id:task.id}),/Two recovery/);for(const o of ['other','competitor'])await h.fixture(o,{energy:100,fullness:100,warmth:100,materials:{wire:2}});h.now+=1000;const recoveryRace=await Promise.allSettled(['other','competitor'].map(o=>act(h.db,o,{action:'recovery_work',id:task.id},h.now)));check(recoveryRace.filter(x=>x.status==='fulfilled').length===1,'The final recovery contract cannot be overassigned by simultaneous citizens');const recoveryOwner=recoveryRace[0].status==='fulfilled'?'other':'competitor';s=await quickEnd(h,recoveryOwner);check(s.cityLife.aftermath.incidents.find(x=>x.id===task.id).recovered&&s.world.coldModifier===1,'Shared recovery lifts lingering boiler pressure');check(s.cityLife.aftermath.paper.find(x=>x.id===crisis.id).body===news,'Recovery cannot rewrite the historical newspaper outcome');await reject(()=>h.start(recoveryOwner,{action:'recovery_work',id:task.id}),/assigned/);
 h.now=crisis.started+5*CITY_DAY_MS;s=await h.read('watcher');check(!s.cityLife.aftermath.incidents.some(x=>x.id===crisis.id),'Lingering effects naturally end after four later cycles');
}
{
 const at=Date.UTC(2026,9,5,1),p={...initial(at),registered:true,energy:30,health:100,fullness:100,warmth:100};
 const exposed=settle(p,at+14400000,world(at+14400000)),protectedRest=settle(p,at+14400000,{...world(at+14400000),tenantHeatWindows:[{from:at+3600000,until:at+10800000}]});
 check(Math.abs(protectedRest.warmth-exposed.warmth-6)<.001,'Offline protection applies only during two actual real hours inside a four-hour absence');
 const h=harness();await h.fixture('mentor',{credits:10,taxDebt:0,taxHold:true,energy:100,district:{day:1,threads:{},contacts:{voss:3},flags:{registryAdvocate:true},decisions:[],cases:{},surveys:[],caseCount:{},responses:0,municipalSales:0}});let s=await h.start('mentor',{action:'clearance'});check(Math.abs(s.citizen.energy-96)<.01&&s.citizen.credits===8&&s.citizen.taxHold&&s.citizen.activity.endsAt-h.now===900000,'Registry advocacy reduces effort but retains fee, deadline, and pending ID hold');s=await h.finish('mentor');check(!s.citizen.taxHold,'Advocated clearance still releases access only at completion');
 const crowd=harness();await crowd.fixture('founder');s=await crowd.start('founder',{action:'tenant_create',name:'Capacity test'});const id=s.tenants.block.id;for(let i=0;i<10;i++){await crowd.fixture('resident'+i);await crowd.start('resident'+i,{action:'tenant_join',id});}for(const o of ['lastA','lastB'])await crowd.fixture(o);crowd.now+=1000;const joins=await Promise.allSettled(['lastA','lastB'].map(o=>act(crowd.db,o,{action:'tenant_join',id},crowd.now)));check(joins.filter(x=>x.status==='fulfilled').length===1&&(await crowd.read('founder')).tenants.members.length===12,'Two simultaneous applicants cannot take the same final building place');
}
console.log(`Passed ${checks} living checks: free housing/legacy waiver, real sleep rewards, bounded paid arrears, prepaid/refunded rent, automatic tax/receipt races, shared tenant goods/messages/repairs, remembered and recurring contacts, clothing wear, and recoverable aftermath.`);
