import assert from 'node:assert/strict';
import { snapshot, act } from '../worker/game.js';
import { harness } from './test-harness.mjs';
const h=harness(),db=h.db;let checks=0;
const read=async owner=>{await h.fixture(owner);return h.read(owner);};
const action=async(owner,input)=>{await h.fixture(owner);return h.action(owner,input);};
const check=(condition,label)=>{assert.ok(condition,label);checks++;};
const reject=async operation=>{await assert.rejects(operation);checks++;};
async function supply(owner,values){const s=await read(owner);db.sqlite.prepare('UPDATE citizens SET data=? WHERE owner=?').run(JSON.stringify({...s.citizen,...values}),owner);}
let s=await read('unbound');check(s.citizen.alignment===0&&s.citizen.coherence===68&&s.forces.balance===0,'Existing citizens receive neutral signal defaults');
await reject(()=>action('unbound',{action:'rite',id:'order'}));
check((await read('unbound')).forces.interventions===0&&(await read('unbound')).citizen.credits===9,'Missing fragment does not change citizen or shared influence');
await reject(()=>action('unbound',{action:'rite',id:'__proto__'}));
await supply('unbound',{energy:0});await reject(()=>action('unbound',{action:'rite',id:'chaos'}));
check((await read('unbound')).forces.balance===0&&(await read('unbound')).citizen.credits===9,'Insufficient energy cannot mint rite credits or influence');
await supply('unbound',{energy:100,fullness:100,warmth:100});
s=await action('unbound',{action:'rite',id:'chaos'});
check(s.citizen.credits===13&&s.citizen.alignment===-12&&s.citizen.coherence===60&&s.citizen.heat===8&&s.citizen.energy===94,'Chaos rite applies declared private costs and rewards');
check((await read('observer')).forces.balance===-12,'Another citizen observes shared influence');
await reject(()=>action('unbound',{action:'rite',id:'order'}));
await supply('canon',{scrap:1,energy:100,fullness:100,warmth:100});s=await action('canon',{action:'rite',id:'order'});
check(s.forces.balance===0&&s.citizen.scrap===0&&s.citizen.rep===1&&s.citizen.coherence===76,'Order rite consumes a fragment and offsets Chaos');
await read('a');await read('b');h.now+=1000;
const together=await Promise.allSettled([act(db,'a',{action:'rite',id:'chaos'},h.now),act(db,'b',{action:'rite',id:'chaos'},h.now)]);
check(together.every(r=>r.status==='fulfilled')&&(await read('observer')).forces.balance===-24,'Concurrent citizens accumulate influence without a lost update');
s=await read('observer');check(s.forces.dominance==='chaos'&&Math.abs(s.world.securityModifier-(-.1+s.world.citySecurityModifier))<.001&&s.world.contrabandPay===28,'Chaos dominance changes checkpoints and package pay');
check(s.goods.find(g=>g.id==='bread').price===4+s.world.foodModifier&&s.goods.find(g=>g.id==='soup').price===6+s.world.foodModifier,'Chaos dominance raises only food prices');
await supply('runner',{energy:100,health:100,fullness:100,warmth:100});
const originalRandom=crypto.getRandomValues.bind(crypto);crypto.getRandomValues=array=>{array.fill(0xffffffff);return array;};
try{s=await action('runner',{action:'crime',id:'smuggle'});check(s.citizen.credits===37,'Successful package run uses the shared Chaos pay');}finally{crypto.getRandomValues=originalRandom;}
await read('duplicate');h.now+=1000;
const same=await Promise.allSettled([act(db,'duplicate',{action:'rite',id:'chaos'},h.now),act(db,'duplicate',{action:'rite',id:'chaos'},h.now)]);
check(same.filter(r=>r.status==='fulfilled').length===1&&(await read('duplicate')).citizen.credits===13,'Concurrent duplicate rite rewards the citizen once');
check((await read('observer')).forces.balance===-36,'Concurrent duplicate rite affects the city once');
const before=(await read('observer')).world.day;h.now+=21600000;s=await read('observer');
check(s.forces.balance===0&&s.forces.interventions===0&&s.world.day===before+1,'The shared signal resets on a new city day');
s=await action('unbound',{action:'rite',id:'chaos'});check(s.citizen.alignment===-24&&s.citizen.lastRiteDay===before+1,'Private alignment persists and the daily rite becomes available');
h.now+=21600000;await read('story');s=await action('story',{action:'encounter',id:'signal',node:'start',choice:'canon'});
check(s.forces.balance===12&&s.citizen.alignment===12&&s.citizen.story.decisions.length===1,'A personal encounter atomically changes private history and the shared signal');
await reject(()=>action('story',{action:'encounter',id:'signal',node:'start',choice:'wound'}));
check((await read('observer')).forces.balance===12,'A replayed story cannot change shared influence');
await supply('stabilizer',{scrap:1});s=await action('stabilizer',{action:'rite',id:'order'});
check(s.forces.dominance==='order'&&Math.abs(s.world.securityModifier-(.1+s.world.citySecurityModifier))<.001&&s.world.contrabandPay===24,'Order dominance increases capture risk without a contraband bonus');
check(s.goods.find(g=>g.id==='bread').price===Math.max(1,2+s.world.foodModifier)&&s.goods.find(g=>g.id==='soup').price===Math.max(1,4+s.world.foodModifier),'Order dominance discounts rations and broth');
db.sqlite.prepare('UPDATE forces SET balance=95 WHERE id=?').run(s.forces.id);await supply('cap',{scrap:1});s=await action('cap',{action:'rite',id:'order'});check(s.forces.balance===100,'Order influence is capped at 100');
db.sqlite.prepare('UPDATE forces SET balance=-95 WHERE id=?').run(s.forces.id);s=await action('floor',{action:'rite',id:'chaos'});check(s.forces.balance===-100,'Chaos influence is capped at -100');
check(db.sqlite.prepare('SELECT count(*) n FROM action_guards').get().n===0,'Force transaction guards do not accumulate');
console.log(`Passed ${checks} Order/Chaos checks: compatibility, costs, daily limits, shared influence, concurrent rites, story effects, prices, contraband pay, bounds, and day reset.`);
