const previousChoice=(p,id,choice)=>p.district.threads[id]?.choices?.includes(choice)||p.district.decisions.some(x=>x.thread===id&&x.choice===choice);
const originalContacts={ration:'neri',sabotage:'esra',permit:'voss',shift:'esra'};
const resolvedThread=(p,id)=>p.district.threads[id]?.node==='done';
const contactChoice=(id,label,preview,outcome,extra={})=>({id,label,preview,outcome,next:'done',...extra});
const checkin=(name,contact,art,eligible,title,text,choices,follow)=>({name,contact,speaker:({neri:'Neri / Bunkhouse IX',esra:'Esra / Boiler crew',voss:'Clerk Voss / Registry',rook:'Rook / Unlicensed routes'})[contact],art,eligible,nodes:{found:{title,text,choices:choices.map(c=>({...c,next:'follow',wait:60000}))},follow:{title:'A name that means something.',text:follow,choices:[contactChoice('answer','Answer their message.','No energy · Contact +1','You answer. The exchange becomes part of your relationship, not another discarded signal.',{relations:1})]}}});
export const contactThreads={
 neri_return:checkin('The blanket at the end of the row','neri','bunkhouse',p=>resolvedThread(p,'ration')&&previousChoice(p,'ration','return'),'Neri remembers the returned card.','Neri saved you a place away from the broken window. There is no heat to offer. She asks whether you will help mend the communal blankets or learn the stitching pattern.',[
 contactChoice('sew','Bring one fabric for the blanket pile.','−1 fabric · Neri +2 · Mending lesson','Your fabric joins the blankets used by the next arrival.',{cost:{cloth:1},relations:2,flag:'mendingLesson'}),contactChoice('learn','Listen while she shows the stitching.','No energy · Neri +1 · Mending lesson','Neri teaches you a stitch that holds in wet cloth.',{relations:1,flag:'mendingLesson'})],'Neri shows you how to mend your jacket with less wasted effort. Mending now costs two energy instead of three.'),
 neri_sale:checkin('The price of a missing meal','neri','bunkhouse',p=>resolvedThread(p,'ration')&&previousChoice(p,'ration','sell'),'Neri knows where her card went.','The broker repeated your name. Neri has another card now, but she remembers waiting hungry while you were paid. You can acknowledge it, make restitution, or refuse the conversation.',[
 contactChoice('repay','Return the two credits you received.','−2 CR · Neri +3 · Restitution recorded','You return the money. It does not undo the lost meal, but Neri accepts the effort.',{cost:{credits:2},relations:3,flag:'neriRestitution'}),contactChoice('admit','Admit what you did.','No energy · Neri +1','You tell her why you took the money. She hears you without promising forgiveness.',{relations:1}),contactChoice('dismiss','Tell her to take it up with the broker.','Neri −2','Neri closes the door. The block now has a story about your name.',{relations:-2})],'The next message carries the distance your response created. People can change their opinion; the record still remembers.'),
 neri_seal:checkin('The number in the scanner','neri','registry',p=>resolvedThread(p,'ration')&&previousChoice(p,'ration','forge'),'A borrowed number comes home.','Neri received a scanner notice for a journey she never made. She asks whether you erased the copied seal or passed its route to Rook. She already knows a copy existed.',[
 contactChoice('own','Acknowledge copying the seal.','Neri +1 · Heat +1','You acknowledge the copy and give her enough information to dispute the notice.',{relations:1,delta:{heat:1}}),contactChoice('deny','Deny knowing anything about the number.','Neri −2 · Chaos +1','The denial becomes another part of the notice.',{relations:-2,delta:{alignment:-1}})],'Neri keeps the scanner paper. Helping later will matter, but the copied card cannot be made unremembered.'),
 esra_evidence:checkin('The contractor returns','esra','workshop',p=>resolvedThread(p,'sabotage')&&previousChoice(p,'sabotage','report'),'Esra kept the stamp you reported.','The contractor asks for the evidence back. Esra offers a public repair rota instead: document which lines fail so the next outage cannot be sold as a coincidence.',[
 contactChoice('record','Help keep a repair record.','Esra +2 · Boiler contact','You put your name beside the observed failures.',{relations:2,flag:'boilerContact'}),contactChoice('quiet','Ask Esra to keep your name out of it.','Esra −1 · No heat or reward','Esra records the work without your name.',{relations:-1})],'The crew will recognize your part in this record when the next failure arrives.'),
 esra_parts:checkin('What the cutters erased','esra','workshop',p=>resolvedThread(p,'sabotage')&&previousChoice(p,'sabotage','strip'),'Esra remembers the destroyed stamp.','Your salvaged parts came from the only stamped assembly. The crew has copper now and no evidence. Esra asks for one wire to finish the practical repair.',[
 contactChoice('wire','Contribute one wire to the crew.','−1 wire · Esra +2 · Trust +1','You bring copper. It repairs one relationship more slowly than it repairs a relay.',{cost:{wire:1},relations:2,delta:{rep:1},flag:'boilerContact'}),contactChoice('refuse','Keep the wire for your own needs.','Esra −1','You keep the parts. The crew must find another supplier.',{relations:-1})],'Esra distinguishes between the evidence you erased and the help you offer now.'),
 voss_address:checkin('The applicant clocks in','voss','registry',p=>resolvedThread(p,'permit')&&previousChoice(p,'permit','address'),'Voss sends a corrected timecard.','The citizen whose address you corrected has completed a shift. Voss asks you to check the public appeal form; many new arrivals confuse paying debt with clearing their ID.',[
 contactChoice('explain','Help make the appeal instructions readable.','Voss +2 · Registry advocate','You correct the confusing instructions without changing the law.',{relations:2,flag:'registryAdvocate'}),contactChoice('copy','Keep a copy for your own records.','Voss +1 · Registry advocate','You keep the form and Voss’s signed contact entry.',{relations:1,flag:'registryAdvocate'})],'Voss can vouch that you understand the review. Registry clearance still takes its normal time and fee, but costs two less energy.'),
 voss_gap:checkin('A building that no longer exists','voss','registry',p=>resolvedThread(p,'permit')&&previousChoice(p,'permit','quiet'),'Voss notices the obsolete address.','A parcel was scanned at the building you kept in your route map. The Registry asks for an explanation. You can surrender the gap or continue withholding it.',[
 contactChoice('correct','Correct the map now.','Prepared route removed · Voss +1 · Order +1','The obsolete address enters the correction list.',{clearPlan:true,relations:1,delta:{alignment:1}}),contactChoice('withhold','Keep the route private.','Voss −1 · Heat +2','The gap remains useful, and your file acquires a note.',{relations:-1,delta:{heat:2}})],'A quiet route is still a route through someone else’s paperwork. Voss will remember how you answered.'),
 rook_test:checkin('A delivery with a real name','rook','neural',p=>p.district.flags.rookContact,'Rook tests what your word is worth.','Rook asks you to compare a crate number with one trace. The public manifest is legitimate; the private route pays sooner. This is a small test before larger deliveries.',[
 contactChoice('public','Use one trace to preserve the manifest.','−1 trace · Rook +1 · Trust +1','Rook learns that you will verify a name before moving a crate.',{cost:{data:1},relations:1,delta:{rep:1},flag:'rookVerified'}),contactChoice('private','Deliver the trace through Rook’s private relay.','−1 trace · +2 unreported CR · Heat +3 · Rook +2','The private relay pays for the trace and remembers your reliability.',{cost:{data:1},relations:2,delta:{credits:2,heat:3,alignment:-1},flag:'rookReliable'}),contactChoice('wait','Tell Rook you cannot spare a trace.','No energy · No reward','Rook leaves the number with you and finds another runner.')],'The next delivery depends on the kind of promise you made, not merely on the credits you carry.'),
 neri_room:checkin('The door you can close','neri','housing',p=>['room','flat'].includes(p.housing)&&(p.district.contacts.neri||0)>0,'Neri notices your new room.','A locked door changes your evenings. Neri asks whether you will still answer the bunkhouse channel when a new arrival needs practical help.',[
 contactChoice('stay','Keep answering the building channel.','Neri +2 · Mutual aid recorded','You give the neighbors a way to reach you.',{relations:2,flag:'mutualAid'}),contactChoice('private','Keep the new address private.','Neri −1','The door stays closed when the channel calls.',{relations:-1})],'Privacy and belonging can coexist. The choice you made tells the block how much to expect.'),
 esra_failure:checkin('After the warning stopped','esra','workshop',(p,w)=>w.aftermath?.some(x=>!x.recovered)&&(p.district.contacts.esra||0)>0,'Esra is counting what remains.','A failed district response has left real damage. The recovery board pays for practical work. Esra asks you to check which supplies the crew lacks before another cycle passes.',[
 contactChoice('board','Compare the recovery contracts and building shelf.','Esra +2 · Recovery contact','You identify the supplies needed for recovery instead of treating the old warning as finished.',{relations:2,flag:'recoveryContact'}),contactChoice('blame','Publish an accusation without checking the record.','Esra −1 · Heat +1','The accusation spreads faster than the recovery plan.',{relations:-1,delta:{heat:1}})],'The district newspaper will keep the failed response. Its aftermath can still be repaired.'),
 voss_desk:checkin('Your first signed file','voss','registry',p=>p.official,'Voss reads the stamp beside your name.','You now process the forms you once queued for. A disputed file is waiting on your earned case desk. Voss asks what you intend your signature to mean.',[
 contactChoice('audit','Commit to documenting your decisions.','Voss +2 · Order +1','You leave a trail that another clerk can audit.',{relations:2,delta:{alignment:1}}),contactChoice('access','Say that access itself is worth a fee.','Voss −1 · Rook contact · Chaos +1','Voss closes the file. Rook hears that a new stamp may be available.',{relations:-1,flag:'rookContact',delta:{alignment:-1}})],'The appointment did not erase the citizen who arrived on the train. Your case choices will make the signature visible.'),
 esra_badge:checkin('The copper behind the badge','esra','transit',p=>p.security,'Esra recognizes your uniform.','The worker behind the checkpoint has the same repair copper you used to scavenge. Esra asks whether your badge will help evidence travel or simply make a queue longer.',[
 contactChoice('receipt','Promise to examine the worker’s receipt.','Esra +2 · Trust +1','You promise to read the evidence before making the worker wait.',{relations:2,delta:{rep:1}}),contactChoice('orders','Say that a flag is enough.','Esra −1 · Order +1','Esra keeps the receipt for someone who will read it.',{relations:-1,delta:{alignment:1}})],'The security desk still requires a real decision. A uniform changes what you can do with the copper.'),
};
export const recurringContacts={
 blanket_round:checkin('The blanket rota','neri','bunkhouse',p=>(p.district.contacts.neri||0)>=1,'The bunkhouse has another arrival.','Neri asks whether you can spare a fabric strip or an introduction. The next citizen has joined the city as it is, with a cold bunk and an empty pocket.',[contactChoice('fabric','Bring one fabric to the rota.','−1 fabric · Neri +2','Your strip becomes a patched blanket for the next arrival.',{cost:{cloth:1},relations:2}),contactChoice('introduce','Explain the free bunk and relief queue.','No energy · Neri +1','You make the next arrival’s first evening less confusing.',{relations:1})],'The arrival remains part of this cycle’s block history.'),
 repair_rota:checkin('The maintenance notebook','esra','workshop',p=>(p.district.contacts.esra||0)>=1,'Esra has a new page to fill.','The crew compares yesterday’s reported repairs with today’s complaints. She wants an observation from your route, not another paid shift.',[contactChoice('report','Describe what you saw on your route.','No energy · Esra +1','Your observation enters the maintenance notebook.',{relations:1}),contactChoice('copper','Bring a wire with the observation.','−1 wire · Esra +2','You bring a repair supply as well as a useful report.',{cost:{wire:1},relations:2})],'The crew uses the notebook when deciding where to send the next warning.'),
 ledger_round:checkin('A line in the account book','voss','registry',p=>(p.district.contacts.voss||0)>=1,'Voss checks a fresh batch of obligations.','The Registry bulletin lists deadlines and reserves. Voss asks you to compare your tax record with the message before repeating it to a neighbor.',[contactChoice('read','Check the public instructions.','No energy · Voss +1','You compare the record with the instructions. Existing tax holds still require clearance.',{relations:1}),contactChoice('ignore','Leave the message unread.','No reward','The bulletin remains on the public relay.')],'A familiar clerk can explain the law; familiarity does not pay your debt.'),
 route_round:checkin('The courier’s weather report','rook','neural',p=>p.district.flags.rookContact,'Rook wants to know which gates are watching.','The route report changes with the district, while a prepared scanner gap still expires every cycle. Rook asks for a trace or a patient account of what you saw.',[contactChoice('trace','Share one signal trace.','−1 trace · Rook +2 · One prepared route','Rook compares the trace and marks one quiet route for this cycle.',{cost:{data:1},relations:2,plan:'quiet'}),contactChoice('talk','Describe the public checkpoint bulletin.','No energy · Rook +1','You describe the bulletin without selling another citizen’s number.',{relations:1})],'Reliable information makes a runner useful. Heat and arrest risk still follow an operation.'),
};
export function offerContacts(p,w){
 const d=p.district;if(!d||d.offerDay===w.day||Object.values(d.threads).filter(t=>t.template&&t.node!=='done').length>=2)return;
 let choice=Object.entries(contactThreads).find(([id,t])=>!d.threads[id]&&t.eligible(p,w));
 if(!choice){const pool=Object.entries(recurringContacts).filter(([,t])=>t.eligible(p,w)&&!Object.entries(originalContacts).some(([id,contact])=>contact===t.contact&&p.district.threads[id]&&p.district.threads[id].node!=='done'));if(pool.length)choice=pool[(w.day-1)%pool.length];}
 if(!choice)return;const [id,t]=choice,key=Object.hasOwn(recurringContacts,id)?id+'-'+w.day:id;d.threads[key]={template:id,node:'found',readyAt:w.now,discoveredAt:w.now};d.offerDay=w.day;
 for(const [key,t] of Object.entries(d.threads))if(t.template&&Object.hasOwn(recurringContacts,t.template)&&t.node==='done'&&t.discoveredAt<w.now-20*21600000)delete d.threads[key];
}
