import {reportedPaymentStatement} from './living.js';
// Server-owned skill practice, unique salvage, restricted supplies and custody.
export const practicalSkills={electronics:{name:'Electronics',description:'Battery replacement, soldering and live relay repairs.',icon:'energy'},mechanics:{name:'Mechanics',description:'Bearings, hand generators and municipal machinery.',icon:'jobs'},tailoring:{name:'Tailoring',description:'Weather linings, field dressings and uniform work.',icon:'coat'},signal:{name:'Signal analysis',description:'Legal diagnostics, encrypted memories and illicit terminal access.',icon:'lock'}};
export const workshopItems={tea:{name:'Salvage tea',effect:'−10 stress, +4 warmth',icon:'soup'},cigarettes:{name:'Plain cigarettes',effect:'−12 stress, −0.5 health',icon:'box'},nightglass:{name:'Nightglass',effect:'+18 energy; after 30 minutes −12 energy, +15 stress, −2 health',icon:'energy',contraband:true},veil:{name:'Veil',effect:'−30 stress, +8 coherence; after 30 minutes −8 energy, −12 coherence',icon:'lock',contraband:true},lining:{name:'Weather lining',effect:'+18 warmth, −20 clothing wear',icon:'coat'},cell:{name:'Rebuilt power cell',effect:'Repair part for handheld devices',icon:'energy'}};
export const advancedRecipes={
 tea:{name:'Brew salvage tea',skill:'tailoring',level:0,seconds:25,energy:2,cost:{cloth:1},xp:1,description:'Filter the municipal tea ration through clean cloth.'},
 cell:{name:'Rebuild a power cell',skill:'electronics',level:0,seconds:45,energy:4,cost:{wire:1,circuit:1},xp:3,description:'A simple contact replacement at the communal bench.'},
 lining:{name:'Stitch a weather lining',skill:'tailoring',level:0,seconds:50,energy:4,cost:{cloth:3},xp:3,description:'A fitted lining for one cold outing.'},
 cigarettes:{name:'Roll reclaimed cigarettes',skill:'tailoring',level:0,seconds:30,energy:2,cost:{cloth:1,leaf:1},xp:1,description:'One pack from fictional civic leaf stock. Comfort costs a little health.'},
 nightglass:{name:'Seal Nightglass',skill:'electronics',level:1,seconds:65,energy:6,cost:{gel:1,circuit:1},xp:2,description:'An invented restricted stimulant. Carrying it risks seizure and a sentence.'},
 veil:{name:'Bind Veil',skill:'signal',level:1,seconds:65,energy:6,cost:{gel:1,data:2},xp:2,description:'An invented signal sedative. The calm ends in a coherence crash.'},
};
export const deviceKinds={pda:{name:'Pocket civic terminal',function:'Legal signal diagnostics recover one extra trace.',skill:'electronics',art:'repaired-pda'},radio:{name:'Field receiver',function:'Illicit terminal detection risk is 5 percentage points lower.',skill:'signal',art:'field-receiver'},lamp:{name:'Hand generator lamp',function:'Idle warmth loss is 0.2 lower per city hour.',skill:'mechanics',art:'hand-generator-lamp'}};
const wsBound=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
const wsNeed=(ok,message)=>{if(!ok)throw Object.assign(new Error(message),{status:400});};
export const skillLevel=xp=>xp>=40?3:xp>=18?2:xp>=6?1:0;
export function workshopState(p,day){
 p.skills??={};for(const id of Object.keys(practicalSkills))p.skills[id]??={xp:0};p.devices??=[];p.activeDevice??=null;p.stress??=15;p.effects??=[];p.locker??={};
 p.workbench??={};if(p.workbench.day!==day)p.workbench={day,practice:{},lessons:[],finds:0,hacks:[],scans:0,broker:0,comfortAt:0};
 for(const id of Object.keys(workshopItems))p[id]??=0;
 p.offenses??=0;return p;
}
export function awardSkill(p,id,amount,day){workshopState(p,day);if(!practicalSkills[id])return;const practiced=p.workbench.practice[id]||0,gain=Math.max(0,Math.min(amount,12-practiced));p.skills[id].xp+=gain;p.workbench.practice[id]=practiced+gain;}
export function equippedDevice(p,kind){return p.devices?.some(d=>d.id===p.activeDevice&&d.condition==='repaired'&&(!kind||d.kind===kind));}
export function skillWorkBonus(p,job){const id=job.skill||({mnemonic:'electronics',transit:'mechanics',civic:'tailoring',recovery:'mechanics'}[job.career]),level=skillLevel(p.skills?.[id]?.xp||0);return {skill:id,level,pay:level,energy:level};}
function wsBlocked(p,w,energy=0){return !p.registered?'Register first.':p.camp?.active?'You are assigned to the camp.':p.activity?'Finish your shift.':p.errand?'Finish your short task.':p.detainedUntil>w.now?'Serve your detention first.':p.health<15?'Use relief or treatment first.':p.energy<energy?`Need ${energy} energy.`:p.street.count>=10?'Ten short tasks per cycle.':null;}
function wsStart(p,w,{id,label,seconds,energy=0,reward={},meta={},art='technical-workbench',count=true}){wsNeed(!p.errand,'Finish your short task.');wsNeed(p.energy>=energy,`Need ${energy} energy.`);p.energy-=energy;if(count)p.street.count++;p.errand={action:'workbench',id,label,art,started:w.now,endsAt:w.now+seconds*1000,reward,expansion:meta,message:`Completed ${label.toLowerCase()}.`};return {message:`Started ${label.toLowerCase()}: ${seconds} seconds, ${energy} energy.`,endsAt:p.errand.endsAt,metrics:{}};}
function wsCost(p,cost){for(const [id,n]of Object.entries(cost||{}))wsNeed((p.materials[id]||0)>=n,`Need ${n} ${id}.`);for(const[id,n]of Object.entries(cost||{}))p.materials[id]-=n;}
export function contrabandCount(p){return (p.materials?.gel||0)+(p.nightglass||0)+(p.veil||0);}
export function inspectionRisk(p,w){return wsBound(.3+p.heat/250+(w.inspection?.15:0)+(w.securityModifier||0),.1,.9);}
export const hackingContracts={diagnostic:{name:'Public relay diagnostic',level:0,illegal:false,seconds:40,energy:4,cost:{},description:'Legal signal practice. Recover one trace, or two with an equipped repaired PDA.'},echo:{name:'Recover an encrypted echo',level:1,illegal:false,seconds:65,energy:6,cost:{data:1},description:'Requires a repaired handheld. Recover two traces and 2 reported credits.'},manifest:{name:'Alter a civic manifest',level:1,illegal:true,seconds:75,energy:7,cost:{data:2},description:'Fictional terminal intrusion. Success pays 5 unreported credits; detection confiscates carried contraband and records an offense.'},buried:{name:'Open the buried contract',level:2,illegal:true,seconds:90,energy:8,cost:{data:2,circuit:1},description:'Recover a hidden freight contract and 8 unreported credits. Detection records an offense.'}};
function deviceRepairQuote(p,d){const skill=d.fault==='encrypted'?'signal':deviceKinds[d.kind].skill,level=d.fault==='battery'?0:1;const cost=d.fault==='battery'?{wire:1,circuit:1}:d.fault==='encrypted'?{data:2,circuit:1}:{wire:2,circuit:1};return {skill,level,cost,seconds:60,energy:5,blocked:d.condition!=='broken'?'Already functional.':!d.diagnosed?'Diagnose the fault first.':skillLevel(p.skills[skill].xp)<level?`Requires ${practicalSkills[skill].name} level ${level}.`:!(d.fault==='battery'&&p.cell>0)&&Object.entries(cost).some(([k,n])=>(p.materials[k]||0)<n)?'Missing repair parts.':null};}
export async function workshopSnapshot(db,p,w){workshopState(p,w.day);const offers=(await db.prepare('SELECT o.*,c.name FROM device_offers o JOIN citizens c ON c.id=o.seller WHERE o.status=0 ORDER BY o.created DESC LIMIT 30').all()).results;return {skills:Object.entries(practicalSkills).map(([id,s])=>({id,...s,xp:p.skills[id].xp,level:skillLevel(p.skills[id].xp),next:[6,18,40][skillLevel(p.skills[id].xp)]||null,practice:p.workbench.practice[id]||0,lessonUsed:p.workbench.lessons.includes(id)})),recipes:Object.entries(advancedRecipes).map(([id,r])=>({id,...r,blocked:wsBlocked(p,w,r.energy)||(skillLevel(p.skills[r.skill].xp)<r.level?`Requires ${practicalSkills[r.skill].name} level ${r.level}.`:Object.entries(r.cost).some(([k,n])=>p.materials[k]<n)?'Missing materials.':null)})),items:workshopItems,devices:p.devices.map(d=>({...d,...deviceKinds[d.kind],repair:deviceRepairQuote(p,d),equipped:d.id===p.activeDevice})),offers:offers.map(o=>({...o,device:JSON.parse(o.data)})),blocked:wsBlocked(p,w),findBlocked:wsBlocked(p,w,5)||(p.workbench.finds>=2?'Two device finds per cycle.':p.devices.length>=8?'Keep at most eight devices.':null),hacks:Object.entries(hackingContracts).map(([id,h])=>({id,...h,risk:h.illegal?wsBound(.35+p.heat/250-skillLevel(p.skills.signal.xp)*.06-(equippedDevice(p,'radio')?.05:0),.1,.85):0,blocked:wsBlocked(p,w,h.energy)||(p.workbench.hacks.includes(id)?'Completed or accepted this cycle.':skillLevel(p.skills.signal.xp)<h.level?`Requires signal analysis level ${h.level}.`:id!=='diagnostic'&&!equippedDevice(p)?'Equip a repaired handheld.':Object.entries(h.cost).some(([k,n])=>p.materials[k]<n)?'Missing materials.':null)})),inspection:{risk:inspectionRisk(p,w),carried:contrabandCount(p),used:p.workbench.scans>0,blocked:wsBlocked(p,w,2)||(p.workbench.scans?'One checkpoint crossing per cycle.':null)},camp:p.camp||null,campProduction:(await db.prepare('SELECT goods,sum(quantity) quantity FROM camp_production WHERE completes<=? GROUP BY goods').bind(w.now).all()).results};}
export function enterCamp(p,now,reason){
 if(p.camp?.active)return;p.camp={id:crypto.randomUUID(),active:true,started:now,reason,required:3,completed:0,helped:false,escapeTried:false,appealed:false};p.detainedUntil=0;p.criminalHold=true;p.activeDevice=null;p.stress=wsBound(p.stress+15);
}
function wsRelease(p,now,escaped=false){const pause=Math.max(0,now-p.camp.started);p.nextRentAt+=pause;p.taxDeadline+=pause;p.camp.active=false;p.camp.released=now;p.camp.escaped=escaped;p.detainedUntil=0;p.health=Math.max(25,p.health);p.energy=Math.max(20,p.energy);p.fullness=Math.max(24,p.fullness);p.heat=escaped?wsBound(p.heat+20):Math.min(p.heat,20);}
export function completeWorkshop(p,a,day){
 const m=a.expansion;if(!m)return;const when=a.endsAt;workshopState(p,day);
 if(m.skill)awardSkill(p,m.skill,m.xp||1,day);
 if(m.device){p.devices.push(m.device);}
 if(m.lessonContact&&p.district){p.district.contacts[m.lessonContact]=(p.district.contacts[m.lessonContact]||0)+1;}
 if(m.diagnose){const d=p.devices.find(d=>d.id===m.diagnose);if(d)d.diagnosed=true;}
 if(m.repair){const d=p.devices.find(d=>d.id===m.repair);if(d&&d.condition==='broken'){d.condition='repaired';d.quality=1+skillLevel(p.skills[m.skill].xp);d.repairedAt=when;}}
 if(m.stress)p.stress=wsBound(p.stress+m.stress);
 if(m.crash)p.effects.push({...m.crash,at:when+1800000});
 if(m.inspect||m.detected){if(m.detected){p.materials.gel=0;p.nightglass=0;p.veil=0;p.credits-=Math.min(p.credits,5);p.offenses++;p.criminalHold=true;p.heat=wsBound(p.heat+12);if(m.carried>=3||p.offenses>=2)enterCamp(p,when,'Repeated or bulk contraband offense.');}}
 if(m.campUnit&&p.camp?.active&&p.camp.id===m.campUnit){p.camp.completed=Math.min(p.camp.required,p.camp.completed+1);p.stress=wsBound(p.stress+4);}
 if(m.escape){if(m.escaped)wsRelease(p,when,true);else p.heat=wsBound(p.heat+10);}
 if(m.hiddenContract){p.hiddenContract=true;}
}
export function settleEffects(p,until){for(const x of p.effects||[]){if(x.at>until)continue;p.energy=wsBound(p.energy-(x.energy||0));p.health=wsBound(p.health-(x.health||0),10,100);p.coherence=wsBound(p.coherence-(x.coherence||0));p.stress=wsBound(p.stress+(x.stress||0));}p.effects=(p.effects||[]).filter(x=>x.at>until);}
export async function workshopAction(db,p,c,input,w,op,random){
 workshopState(p,w.day);const extra=[],checks=[],make=(sql,...args)=>db.prepare(sql).bind(...args);let result={metrics:{}};
 const guard=(sql,...args)=>checks.push(make('INSERT INTO action_guards (id,valid) VALUES (?,COALESCE(('+sql+'),0))',op+'ws'+checks.length,...args));
 const id=input.id;
 if(input.action.startsWith('camp_')){
  wsNeed(p.camp?.active,'You are not assigned to a labor camp.');wsNeed(!p.errand&&!p.activity,'Finish your current assignment.');
  if(input.action==='camp_release'){wsNeed(p.camp.completed>=p.camp.required,'Finish all three production orders.');wsRelease(p,w.now);return {...result,message:'Three orders recorded. You return to the city. Outside billing resumes; your arrest record still needs Registry clearance.',extra,checks};}
  if(input.action==='camp_rest'){result=wsStart(p,w,{id:'camp-rest',label:'Camp meal and bunk rest',seconds:15,reward:{energy:25,fullness:24,warmth:15,health:4},meta:{stress:-8},art:'camp-barracks',count:false});}
  else if(input.action==='camp_help'){wsNeed(!p.camp.helped,'You already helped this inmate.');p.camp.helped=true;result=wsStart(p,w,{id:'camp-help',label:'Share a bench with Ivo',seconds:25,energy:2,reward:{rep:1},meta:{stress:-10},art:'camp-barracks',count:false});p.errand.message='Ivo shows you how to steady the jig. One trust, less stress. Your production quota is unchanged.';}
  else if(input.action==='camp_appeal'){wsNeed(!p.camp.appealed,'Your appeal is recorded.');p.camp.appealed=true;result=wsStart(p,w,{id:'camp-appeal',label:'Refuse a false production count',seconds:25,energy:2,reward:{rep:1},art:'camp-factory',count:false});p.errand.message='The clerk records the goods you actually made. No extra sentence, no false release credit. One trust.';}
  else if(input.action==='camp_escape'){wsNeed(!p.camp.escapeTried,'One escape attempt per sentence.');wsNeed(skillLevel(p.skills.signal.xp)>=2,'Signal analysis level 2 required.');p.camp.escapeTried=true;const escaped=random<.35;result=wsStart(p,w,{id:'camp-escape',label:'Follow the uncounted maintenance route',seconds:60,energy:8,meta:{escape:true,escaped},art:'signal-den',count:false});p.errand.message=escaped?'The service gate accepts a forgotten signature. You escape; heat rises and the arrest hold remains.':'The route closes. Ten heat added; your finite production sentence is unchanged.';}
  else if(input.action==='camp_work'){
   wsNeed(p.camp.completed<p.camp.required,'Your quota is complete. Request release.');const assignments={rations:{name:'Pack municipal rations',skill:'tailoring'},relays:{name:'Assemble heating relays',skill:'electronics',level:1},fabric:{name:'Service the textile loom',skill:'mechanics',level:1}};const a=Object.hasOwn(assignments,id)?assignments[id]:null;wsNeed(a,'Choose a camp assignment.');const level=skillLevel(p.skills[a.skill].xp);wsNeed(level>=(a.level||0),`Requires ${practicalSkills[a.skill].name} level ${a.level}.`);
   result=wsStart(p,w,{id:'camp-work',label:a.name,seconds:Math.max(30,60-level*10),energy:Math.max(3,7-level),meta:{campUnit:p.camp.id,skill:a.skill,xp:2},art:'camp-factory',count:false});result.metrics={output:2,...(id==='relays'?{relief:1}:{})};
   extra.push(make('INSERT INTO camp_production (id,citizen,sentence,goods,quantity,completes) VALUES (?,?,?,?,1,?)',op,c.id,p.camp.id,id,result.endsAt));p.errand.message=`One ${id} order completed for the city. Zero credits; one of three release orders recorded.`;
  }else wsNeed(false,'Unknown camp action.');
  return {...result,extra,checks};
 }
 wsNeed(!p.camp?.active,'Camp assignments are your only work until release.');
 if(input.action==='device_equip'){wsNeed(!p.errand,'Finish your task.');const d=p.devices.find(d=>d.id===id);wsNeed(d?.condition==='repaired','Choose a repaired device.');p.activeDevice=id;return {message:'Repaired device equipped.',extra,checks};}
 if(input.action==='device_list'||input.action==='device_broker'||input.action==='device_dismantle'){
  wsNeed(!p.activity&&!p.errand,'Finish your assignment.');const d=p.devices.find(d=>d.id===id);wsNeed(d,'You do not own that device.');
  if(input.action==='device_list'){wsNeed(Number.isInteger(input.price)&&input.price>=1&&input.price<=50,'Choose 1–50 credits.');const count=await make('SELECT count(*) n FROM device_offers WHERE seller=? AND status=0',c.id).first();wsNeed(count.n<4,'Four device listings at a time.');extra.push(make('INSERT INTO device_offers (id,seller,data,price,status,created) VALUES (?,?,?,?,0,?)',op,c.id,JSON.stringify(d),input.price,w.now));result.message='Device placed in market escrow. Its fault and condition remain visible.';}
  else if(input.action==='device_broker'){wsNeed(p.workbench.broker<1,'One municipal device sale per cycle.');const demand='devices-'+w.day;extra.push(make('INSERT OR IGNORE INTO device_demand (id,remaining) VALUES (?,6)',demand));guard('SELECT 1 WHERE COALESCE((SELECT remaining FROM device_demand WHERE id=?),6)>0',demand);extra.push(make('UPDATE device_demand SET remaining=remaining-1 WHERE id=?',demand));const pay=d.condition==='repaired'?8+(d.quality||1)*2:2;p.credits+=pay;p.workbench.broker++;result.taxGross=pay;result.message=`The municipal refurbisher pays ${pay} reported credits. Six devices needed across the city this cycle.`;}
  else {p.materials.wire++;p.materials.circuit++;result.message='Device dismantled into one wire and one circuit. No skill XP for recycling.';}
  p.devices=p.devices.filter(x=>x.id!==id);if(p.activeDevice===id)p.activeDevice=null;return {...result,extra,checks};
 }
 if(input.action==='device_buy'||input.action==='device_cancel'){
  wsNeed(!p.errand,'Finish your task.');wsNeed(p.devices.length<8,'Keep at most eight devices.');const o=await make('SELECT * FROM device_offers WHERE id=? AND status=0',id).first();wsNeed(o,'That device is no longer offered.');guard('SELECT 1 FROM device_offers WHERE id=? AND status=0',id);const d=JSON.parse(o.data);wsNeed(!p.devices.some(x=>x.id===d.id),'You already own this device.');
  if(input.action==='device_buy'){wsNeed(o.seller!==c.id,'You cannot buy your own offer.');wsNeed(p.credits>=o.price,`Need ${o.price} credits.`);p.credits-=o.price;extra.push(reportedPaymentStatement(db,o.seller,o.price));}
  else wsNeed(o.seller===c.id,'Only the seller can cancel.');extra.push(make('UPDATE device_offers SET status=? WHERE id=?',input.action==='device_buy'?1:2,id));p.devices.push(d);return {message:input.action==='device_buy'?'Device purchased. Its history is preserved.':'Device returned from escrow.',extra,checks};
 }
 if(input.action==='locker_store'||input.action==='locker_take'||input.action==='surrender'){
  wsNeed(!p.activity&&!p.errand,'Finish your assignment.');wsNeed(['gel','nightglass','veil'].includes(id),'Choose a restricted item.');const bag=id==='gel'?p.materials:p;
  if(input.action==='locker_take'){wsNeed(p.locker[id]>0,'Your locker is empty.');p.locker[id]--;bag[id]=(bag[id]||0)+1;}
  else {wsNeed(bag[id]>0,'You do not carry that item.');bag[id]--;if(input.action==='locker_store')p.locker[id]=(p.locker[id]||0)+1;}
  return {message:input.action==='surrender'?'One restricted unit surrendered without a fine.':input.action==='locker_store'?'One unit secured in your municipal locker. Checkpoints scan carried items.':'One restricted unit moved into your bag.',extra,checks};
 }
 if(input.action==='comfort_use'){
  const item=workshopItems[id];wsNeed(item&&!['cell'].includes(id),'Choose a usable item.');wsNeed(!p.errand,'Finish your task.');wsNeed(p[id]>0,'You do not have this supply.');
  if(['tea','cigarettes'].includes(id)){wsNeed(w.now-(p.lastComfortAt||0)>=900000,'Comfort once per city hour.');p.lastComfortAt=w.now;p.stress=wsBound(p.stress-(id==='tea'?10:12));if(id==='tea')p.warmth=wsBound(p.warmth+4);else p.health=wsBound(p.health-.5,10,100);}
  else if(id==='lining'){p.warmth=wsBound(p.warmth+18);p.clothingWear=Math.max(0,p.clothingWear-20);}
  else {wsNeed(p.effects.length===0,'An active street-drug effect must wear off first.');if(id==='nightglass'){p.energy=wsBound(p.energy+18);p.effects.push({at:w.now+1800000,energy:12,stress:15,health:2});}else{p.stress=wsBound(p.stress-30);p.coherence=wsBound(p.coherence+8);p.effects.push({at:w.now+1800000,energy:8,coherence:12});}}
  p[id]--;return {message:`Used ${item.name.toLowerCase()}. ${item.effect}.`,extra,checks};
 }
 const blocked=wsBlocked(p,w);wsNeed(!blocked,blocked);
 if(input.action==='skill_lesson'){wsNeed(Object.hasOwn(practicalSkills,id),'Choose a practical skill.');wsNeed(!p.workbench.lessons.includes(id),'One lesson per skill per cycle.');p.workbench.lessons.push(id);result=wsStart(p,w,{id:'lesson',label:`Communal ${practicalSkills[id].name.toLowerCase()} lesson`,seconds:30,energy:3,meta:{skill:id,xp:2,lessonContact:{electronics:'esra',mechanics:'rook',tailoring:'neri',signal:'voss'}[id]}});}
 else if(input.action==='advanced_craft'){const r=Object.hasOwn(advancedRecipes,id)?advancedRecipes[id]:null;wsNeed(r,'Choose a published recipe.');wsNeed(skillLevel(p.skills[r.skill].xp)>=r.level,`Requires ${practicalSkills[r.skill].name} level ${r.level}.`);wsCost(p,r.cost);result=wsStart(p,w,{id,label:r.name,seconds:r.seconds,energy:r.energy,reward:{[id]:1},meta:{skill:r.skill,xp:r.xp},art:['tea','cigarettes','nightglass','veil'].includes(id)?'comfort-supplies':'technical-workbench'});}
 else if(input.action==='device_find'){wsNeed(p.workbench.finds<2,'Two device finds per cycle.');wsNeed(p.devices.length<8,'Keep at most eight devices.');const kinds=['pda','lamp','radio'],kind=kinds[(p.salvageFinds||0)%3],fault=(p.salvageFinds||0)<2?'battery':(p.salvageFinds||0)%2?'contacts':'encrypted';p.salvageFinds=(p.salvageFinds||0)+1;p.workbench.finds++;const d={id:crypto.randomUUID(),kind,condition:'broken',fault,diagnosed:false,foundAt:w.now};result=wsStart(p,w,{id:'find',label:'Scavenge an abandoned handheld',seconds:45,energy:5,meta:{device:d},art:'broken-pda'});p.errand.message=`Found a broken ${deviceKinds[kind].name.toLowerCase()}. Diagnose, repair, dismantle or sell it.`;}
 else if(input.action==='device_diagnose'){const d=p.devices.find(d=>d.id===id);wsNeed(d&&d.condition==='broken'&&!d.diagnosed,'Choose an undiagnosed broken device.');result=wsStart(p,w,{id:'diagnose',label:'Diagnose the handheld fault',seconds:25,energy:2,meta:{skill:deviceKinds[d.kind].skill,xp:1,diagnose:id}});p.errand.message=`Fault identified: ${d.fault}. The repair requirements are on your workbench.`;}
 else if(input.action==='device_repair'){const d=p.devices.find(d=>d.id===id);wsNeed(d,'Choose an owned device.');const q=deviceRepairQuote(p,d);wsNeed(!q.blocked,q.blocked);if(d.fault==='battery'&&p.cell>0)p.cell--;else wsCost(p,q.cost);result=wsStart(p,w,{id:'repair',label:`Repair ${deviceKinds[d.kind].name.toLowerCase()}`,seconds:q.seconds,energy:q.energy,meta:{skill:q.skill,xp:4,repair:id}});}
 else if(input.action==='hack'){const h=Object.hasOwn(hackingContracts,id)?hackingContracts[id]:null;wsNeed(h,'Choose a fictional terminal contract.');wsNeed(!p.workbench.hacks.includes(id),'Once per contract per cycle.');wsNeed(skillLevel(p.skills.signal.xp)>=h.level,`Requires signal analysis level ${h.level}.`);wsNeed(id==='diagnostic'||equippedDevice(p),'Equip a repaired handheld.');wsCost(p,h.cost);p.workbench.hacks.push(id);const risk=wsBound(.35+p.heat/250-skillLevel(p.skills.signal.xp)*.06-(equippedDevice(p,'radio')?.05:0),.1,.85),detected=h.illegal&&random<risk;
  const reward=detected?{}:id==='diagnostic'?{materials:{data:equippedDevice(p,'pda')?2:1}}:id==='echo'?{materials:{data:2},credits:2,taxGross:2}:id==='manifest'?{credits:5,heat:6}:{credits:8,heat:10};result=wsStart(p,w,{id,label:h.name,seconds:h.seconds,energy:h.energy,reward,meta:{skill:'signal',xp:detected?1:3,detected,carried:contrabandCount(p),hiddenContract:id==='buried'&&!detected},art:'signal-den'});result.metrics=h.illegal?{crime:1}:{freight:1};p.errand.message=detected?'The terminal flags your signature. Carried contraband is seized, up to 5 credits fined; repeated offenses lead to three camp orders.':`Completed ${h.name.toLowerCase()}. Your signal skill improves and the recovered proceeds arrive.`;
 }
 else if(input.action==='checkpoint'){wsNeed(!p.workbench.scans,'One checkpoint crossing per cycle.');p.workbench.scans++;const carried=contrabandCount(p),detected=carried>0&&random<inspectionRisk(p,w);result=wsStart(p,w,{id:'checkpoint',label:'Cross the civic scanner',seconds:30,energy:2,meta:{inspect:true,detected,carried},art:'civic-checkpoint'});p.errand.message=detected?(carried>=3||p.offenses>=1?'Contraband seized. Three municipal production orders replace your freedom.':'Contraband seized. Up to 5 credits fined; your ID carries an arrest hold.'):'The checkpoint clears your carried inventory. No seizure or fine.';}
 else if(input.action==='restricted_salvage'){wsNeed(p.workbench.hacks.indexOf('restricted')<0,'One restricted salvage trip per cycle.');p.workbench.hacks.push('restricted');result=wsStart(p,w,{id:'restricted',label:'Recover a sealed clinic discard',seconds:45,energy:5,reward:{materials:{gel:1,leaf:1}},art:'scavenge'});p.errand.message='One fictional clinic gel and one civic leaf recovered. The gel is contraband even before it is crafted.';}
 else if(input.action==='restricted_steal'){wsNeed(p.criminal.count<3,'Three criminal operations per cycle.');p.criminal.count++;const detected=random<inspectionRisk(p,w);result=wsStart(p,w,{id:'restricted-steal',label:'Lift a sealed clinic crate',seconds:60,energy:7,reward:detected?{}:{materials:{gel:2,leaf:1},heat:8},meta:{detected,carried:contrabandCount(p)},art:'civic-checkpoint'});result.metrics={crime:1};p.errand.message=detected?'The crate beacon identifies you. A fine and arrest record; repeated offenses lead to camp.':'Two fictional restricted gels and one civic leaf enter your bag. Carrying these through scanners is a separate risk.';}
 else if(input.action==='comfort_talk'){wsNeed(!p.workbench.hacks.includes('talk'),'One fireside conversation per cycle.');p.workbench.hacks.push('talk');result=wsStart(p,w,{id:'talk',label:'Talk beside the barrel fire',seconds:25,energy:0,meta:{stress:-12},art:'barrel-fire'});}
 else wsNeed(false,'Unknown workshop action.');
 return {...result,extra,checks};
}
